### ISSUE TITLE
Impossibilité de lancer les tests de certaines sous-apps de façon isolée

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1351]
(Relatif à #1340 et découvert en enquêtant sur #1350)

Par exemple sur `gbfs`, on obtient:

```
mix cmd --app gbfs mix test --color
==> gbfs
Compiling 13 files (.ex)

== Compilation error in file lib/gbfs/controllers/vlille_controller.ex ==
** (CompileError) lib/gbfs/controllers/vlille_controller.ex:114: HTTPoison.Response.__struct__/0 is undefined, cannot expand struct HTTPoison.Response
```

et sur `apps/datagouvfr`, on a:

```
$ mix cmd --app datagouvfr mix test --color
==> datagouvfr

== Compilation error in file test/datagouvfr/client/datasets_test.exs ==
** (CompileError) test/datagouvfr/client/datasets_test.exs:3: module TransportWeb.ConnCase is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/2
    test/datagouvfr/client/datasets_test.exs:3: Datagouvfr.Client.DatasetsTest (module)
# SNIP
```

C'est relié au "code smell" déjà détecté:

https://github.com/etalab/transport-site/blob/b0dcaaa7241757fc22257f36b025aad085897036/apps/datagouvfr/test/datagouvfr/client/datasets_test.exs#L2-L5

(dépendance vers de l'outillage fourni par l'app `transport`)

Rien de super bloquant, mais je le documente ici pour l'instant pour ne pas l'oublier, car on va retomber dessus plus tard pour sûr.

**Comment by thbar** [comment]
Ca m'a embêté aujourd'hui à nouveau, je contourne.

**Comment by thbar** [comment]
Une solution (pas optimale du tout, car on voit tout l'output des autres applications) est d'utiliser `mix test --only focus` et d'ajouter un tag temporairement sur le test:

```elixir
@tag :focus
test "returns properly formatted hrefs" do
  # SNIP
end
```

**Comment by thbar** [comment]
À garder ouvert, je travaille dessus.

**Comment by thbar** [comment]
Ce sujet a continué à avancer mais n'est pas totalement réglé.
