### ISSUE TITLE
Alertes de masse UptimeRobot (GBFS)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1354]
Je suis à présent inscrit aux alertes de monitoring (voir https://status.transport.data.gouv.fr) pour la partie GBFS, qui est une sous-partie de l'application avec un rôle de "proxy modificateur" de données tierces.

Il y a des jours ou je reçois d'un coup (au même moment) de nombreuses alertes, puis ça passe. Je note ce que je sais pour aller enquêter plus tard.

### Symptôme

En étant inscrit à la liste interne "contact", le monitoring UptimeRobot mis en place par Francis remonte régulièrement des erreurs groupées, exemple ce matin à 9h12:

<img width="500" alt="CleanShot 2020-11-12 at 09 54 58@2x" src="https://user-images.githubusercontent.com/10141/98917831-27d38000-24cd-11eb-8e12-ae0603eba65a.png">

En allant dans la console clever-cloud, partie "activity" de "transport-site", je vois un déploiement associé un peu avant:

<img width="375" alt="CleanShot 2020-11-12 at 09 55 57@2x" src="https://user-images.githubusercontent.com/10141/98918571-1179f400-24ce-11eb-9cfa-99191f8a9499.png">

On a probablement un déploiement automatique, qui cause un souci, à vue de nez.

### Code pertinent

Le code de la partie GBFS est [ici](https://github.com/etalab/transport-site/tree/master/apps/gbfs).

On peut voir les routes associées à l'aide de la commande suivante:

```
$ mix phx.routes GBFS.Router
         index_path  GET  /gbfs                                          GBFS.IndexController :index
   montpellier_path  GET  /gbfs/montpellier/gbfs.json                    GBFS.SmooveController :index
   montpellier_path  GET  /gbfs/montpellier/system_information.json      GBFS.SmooveController :system_information
   montpellier_path  GET  /gbfs/montpellier/station_information.json     GBFS.SmooveController :station_information
   montpellier_path  GET  /gbfs/montpellier/station_status.json          GBFS.SmooveController :station_status
    strasbourg_path  GET  /gbfs/strasbourg/gbfs.json                     GBFS.SmooveController :index
# SNIP
```

**Comment by fchabouis** [comment]
Les logs de l'instance avant le redéploiement :

 2020-11-12T09:20:00+01:00 ** (exit) an exception was raised:
2020-11-12T09:20:00+01:00 Request: GET /login/explanation?redirect_path=%2Flogin%2Fexplanation%3Fredirect_path%3D%252Flogin%252Fexplanation%253Fredirect_path%253D%25252Flogin%25252Fexplanation%25253Fredirect_path%25253D%2525252Flogin%2525252Fexplanation%2525253Fredirect_path%2525253D%252525252Flogin%252525252Fexplanation%252525253Fredirect_path%252525253D%25252525252Flogin%25252525252Fexplanation%25252525253Fredirect_path%25252525253D%2525252525252Flogin%2525252525252Fexplanation%2525252525253Fredirect_path%2525252525253D%252525252525252Flogin%252525252525252Fexplanation%252525252525253Fredirect_path%252525252525253D%25252525252525252Flogin%25252525252525252Fexplanation%25252525252525253Fredirect_path%25252525252525253D%2525252525252525252Flogin%2525252525252525252Fexplanation%2525252525252525253Fredirect_path%2525252525252525253D%252525252525252525252Flogin%252525252525252525252Fexplanation%252525252525252525253Fredirect_path%252525252525252525253D%25252525252525252525252Flogin%25252525252525252525252Fexplanation%25252525252525252525253Fredirect_path%25252525252525252525253D%2525252525252525252525252Flogin%2525252525252525252525252Fexplanation%2525252525252525252525253Fredirect_path%2525252525252525252525253D%252525252525252525252525252Flogin%252525252525252525252525252Fexplanation%252525252525252525252525253Fredirect_path%252525252525252525252525253D%25252525252525252525252525252Flogin%25252525252525252525252525252Fexplanation%25252525252525252525252525253Fredirect_path%25252525252525252525252525253D%2525252525252525252525252525252Flogin%2525252525252525252525252525252Fexplanation%2525252525252525252525252525253Fredirect_path%2525252525252525252525252525253D%252525252525252525252525252525252Flogin%252525252525252525252525252525252Fexplanation%252525252525252525252525252525253Fredirect_path%252525252525252525252525252525253D%25252525252525252525252525252525252Flogin%25252525252525252525252525252525252Fexplanation%25252525252525252525252525252525253Fredirect_path%25252525252525252525252525252525253D%2525252525252525252525252525252525252Flogin%2525252525252525252525252525252525252Fexplanation%2525252525252525252525252525252525253Fredirect_path%2525252525252525252525252525252525253D%252525252525252525252525252525252525252Flogin%252525252525252525252525252525252525252Fexplanation%252525252525252525252525252525252525253Fredirect_path%252525252525252525252525252525252525253D%25252525252525252525252525252525252525252Flogin%25252525252525252525252525252525252525252Fexplanation%25252525252525252525252525252525252525253Fredirect_path%25252525252525252525252525252525252525253D%2525252525252525252525252525252525252525252Flogin%2525252525252525252525252525252525252525252Fexplanation%2525252525252525252525252525252525252525253Fredirect_path%2525252525252525252525252525252525252525253D%252525252525252525252525252525252525252525252Fdatasets%252525252525252525252525252525252525252525252Fregion%252525252525252525252525252525252525252525252F12%252525252525252525252525252525252525252525253Forder_by%252525252525252525252525252525252525252525253Dalpha%2525252525252525252525252525252525252525252526page%252525252525252525252525252525252525252525253D3
2020-11-12T09:20:00+01:00 08:19:59.908 request_id=Fka04fzRQaYh7JgAAQ9x [info] Sent 200 in 1ms
2020-11-12T09:20:00+01:00 08:19:59.906 request_id=Fka04fzRQaYh7JgAAQ9x [info] GET /login/explanation
2020-11-12T09:20:00+01:00 (phoenix) lib/phoenix/endpoint/render_errors.ex:62: Phoenix.Endpoint.RenderErrors.__catch__/5
2020-11-12T09:20:00+01:00 (phoenix_html) deps/phoenix_html/lib/phoenix_html/safe.ex:15: Phoenix.HTML.Safe.to_iodata/1
2020-11-12T09:20:00+01:00 (phoenix) lib/phoenix/view.ex:410: Phoenix.View.render_to_iodata/3
2020-11-12T09:20:00+01:00 (phoenix_html) deps/phoenix_html/lib/phoenix_html/safe.ex:1: Phoenix.HTML.Safe.impl_for!/1
2020-11-12T09:20:00+01:00 (transport) lib/transport_web/templates/error/internal_server_error.html.eex:3: TransportWeb.ErrorView."internal_server_error.html"/1
2020-11-12T09:20:00+01:00 (transport) lib/transport_web/templates/layout/app.html.eex:61: TransportWeb.LayoutView."app.html"/1
2020-11-12T09:20:00+01:00 (phoenix) lib/phoenix/controller.ex:729: Phoenix.Controller.__put_render__/5
2020-11-12T09:20:00+01:00 ** (Protocol.UndefinedError) protocol Phoenix.HTML.Safe not implemented for %Plug.Conn.CookieOverflowError{message: "cookie named \"_transport_key\" exceeds maximum size of 4096 bytes"}. This protocol is implemented for: Phoenix.LiveView.Comprehension, Phoenix.LiveView.Rendered, Integer, List, Float, BitString, Tuple, DateTime, NaiveDateTime, Phoenix.HTML.Form, Time, Atom, Date
2020-11-12T09:20:00+01:00 08:19:59.965 [warn] Failed to send Sentry event.
2020-11-12T09:20:00+01:00 (phoenix) lib/phoenix/endpoint/render_errors.ex:77: Phoenix.Endpoint.RenderErrors.instrument_render_and_send/5
2020-11-12T09:20:00+01:00 Event ID: 93b7b493a87a4dca99bff85216ab4663 - "Received 403 from Sentry server: Event dropped due to filter" - {"breadcrumbs":[],"culprit":"Plug.Conn.verify_cookie!/2","environment":"prod","event_id":"93b7b493a87a4dca99bff85216ab4663","exception":[{"module":null,"type":"Plug.Conn.CookieOverflowError","value":"cookie named \"_transport_key\" exceeds maximum size of 4096 bytes"}],"extra":{},"fingerprint":["{{ default }}"],"level":"error","message":"(Plug.Conn.CookieOverflowError) cookie named \"_transport_key\" exceeds maximum size of 4096 bytes","modules":{"certifi":"2.5.1","cowboy":"1.1.2","cowlib":"1.0.2","decimal":"1.9.0","hackney":"1.15.2","idna":"6.0.0","jason":"1.2.2","metrics":"1.0.1","mime":"1.4.0","mimerl":"1.2.0","parse_trans":"","phoenix":"1.4.10","phoenix_pubsub":"1.1.2","plug":"1.10.4","plug_cowboy":"1.0.0","plug_crypto":"1.1.2","ranch":"1.3.2","ssl_verify_fun":"1.1.5","telemetry":"0.4.2","unicode_util_compat":"0.4.1"},"platform":"elixir","release":null,"request":{"cookies":{},"data":{"redirect_path":"/login/explanation?redirect_path=%2Flogin%2Fexplanation%3Fredirect_path%3D%252Flogin%252Fexplanation%253Fredirect_path%253D%25252Flogin%25252Fexplanation%25253Fredirect_path%25253D%2525252Flogin%2525252Fexplanation%2525253Fredirect_path%2525253D%252525252Flogin%252525252Fexplanation%252525253Fredirect_path%252525253D%25252525252Flogin%25252525252Fexplanation%25252525253Fredirect_path%25252525253D%2525252525252Flogin%2525252525252Fexplanation%2525252525253Fredirect_path%2525252525253D%252525252525252Flogin%252525252525252Fexplanation%252525252525253Fredirect_path%252525252525253D%25252525252525252Flogin%25252525252525252Fexplanation%25252525252525253Fredirect_path%25252525252525253D%2525252525252525252Flogin%2525252525252525252Fexplanation%2525252525252525253Fredirect_path%2525252525252525253D%252525252525252525252Flogin%252525252525252525252Fexplanation%252525252525252525253Fredirect_path%252525252525252525253D%25252525252525252525252Flogin%25252525252525252525252Fexplanation%25252525252525252525253Fredirect_path%25252525252525252525253D%2525252525252525252525252Flogin%2525252525252525252525252Fexplanation%2525252525252525252525253Fredirect_path%2525252525252525252525253D%252525252525252525252525252Flogin%252525252525252525252525252Fexplanation%252525252525252525252525253Fredirect_path%252525252525252525252525253D%25252525252525252525252525252Flogin%25252525252525252525252525252Fexplanation%25252525252525252525252525253Fredirect_path%25252525252525252525252525253D%2525252525252525252525252525252Flogin%2525252525252525252525252525252Fexplanation%2525252525252525252525252525253Fredirect_path%2525252525252525252525252525253D%252525252525252525252525252525252Flogin%252525252525252525252525252525252Fexplanation%252525252525252525252525252525253Fredirect_path%252525252525252525252525252525253D%25252525252525252525252525252525252Flogin%25252525252525252525252525252525252Fexplanation%25252525252525252525252525252525253Fredirect_path%25252525252525252525252525252525253D%2525252525252525252525252525252525252Flogin%2525252525252525252525252525252525252Fexplanation%2525252525252525252525252525252525253Fredirect_path%2525252525252525252525252525252525253D%252525252525252525252525252525252525252Flogin%252525252525252525252525252525252525252Fexplanation%252525252525252525252525252525252525253Fredirect_path%252525252525252525252525252525252525253D%25252525252525252525252525252525252525252Flogin%25252525252525252525252525252525252525252Fexplanation%25252525252525252525252525252525252525253Fredirect_path%25252525252525252525252525252525252525253D%2525252525252525252525252525252525252525252Fdatasets%2525252525252525252525252525252525252525252Fregion%2525252525252525252525252525252525252525252F12%2525252525252525252525252525252525252525253Forder_by%2525252525252525252525252525252525252525253Dalpha%25252525252525252525252525252525252525252526page%2525252525252525252525252525252525252525253D3"},"env":{"REMOTE_ADDR":"46.252.181.104","REMOTE_PORT":57266,"REQUEST_ID":"Fka04fzRQaYh7JgAAQ9x","SERVER_NAME":"transport.data.gouv.fr","SERVER_PORT":443},"headers":{"accept":"text/html, application/rss+xml, application/atom+xml, text/xml, text/rss+xml, application/xhtml+xml","accept-encoding":"gzip,deflate","host":"transport.data.gouv.fr","user-agent":"Mozilla/5.0 (compatible; SemrushBot/6~bl; +http://www.semrush.com/bot.html)","x-forwarded-for":"185.191.171.6","x-forwarded-port":"443","x-forwarded-proto":"https"},"method":"GET","query_string":"redirect_path=%2Flogin%2Fexplanation%3Fredirect_path%3D%252Flogin%252Fexplanation%253Fredirect_path%253D%25252Flogin%25252Fexplanation%25253Fredirect_path%25253D%2525252Flogin%2525252Fexplanation%2525253Fredirect_path%2525253D%252525252Flogin%252525252Fexplanation%252525253Fredirect_path%252525253D%25252525252Flogin%25252525252Fexplanation%25252525253Fredirect_path%25252525253D%2525252525252Flogin%2525252525252Fexplanation%2525252525253Fredirect_path%2525252525253D%252525252525252Flogin%252525252525252Fexplanation%252525252525253Fredirect_path%252525252525253D%25252525252525252Flogin%25252525252525252Fexplanation%25252525252525253Fredirect_path%25252525252525253D%2525252525252525252Flogin%2525252525252525252Fexplanation%2525252525252525253Fredirect_path%2525252525252525253D%252525252525252525252Flogin%252525252525252525252Fexplanation%252525252525252525253Fredirect_path%252525252525252525253D%25252525252525252525252Flogin%25252525252525252525252Fexplanation%25252525252525252525253Fredirect_path%25252525252525252525253D%2525252525252525252525252Flogin%2525252525252525252525252Fexplanation%2525252525252525252525253Fredirect_path%2525252525252525252525253D%252525252525252525252525252Flogin%252525252525252525252525252Fexplanation%252525252525252525252525253Fredirect_path%252525252525252525252525253D%25252525252525252525252525252Flogin%25252525252525252525252525252Fexplanation%25252525252525252525252525253Fredirect_path%25252525252525252525252525253D%2525252525252525252525252525252Flogin%2525252525252525252525252525252Fexplanation%2525252525252525252525252525253Fredirect_path%2525252525252525252525252525253D%252525252525252525252525252525252Flogin%252525252525252525252525252525252Fexplanation%252525252525252525252525252525253Fredirect_path%252525252525252525252525252525253D%25252525252525252525252525252525252Flogin%25252525252525252525252525252525252Fexplanation%25252525252525252525252525252525253Fredirect_path%25252525252525252525252525252525253D%2525252525252525252525252525252525252Flogin%2525252525252525252525252525252525252Fexplanation%2525252525252525252525252525252525253Fredirect_path%2525252525252525252525252525252525253D%252525252525252525252525252525252525252Flogin%252525252525252525252525252525252525252Fexplanation%252525252525252525252525252525252525253Fredirect_path%252525252525252525252525252525252525253D%25252525252525252525252525252525252525252Flogin%25252525252525252525252525252525252525252Fexplanation%25252525252525252525252525252525252525253Fredirect_path%25252525252525252525252525252525252525253D%2525252525252525252525252525252525252525252Flogin%2525252525252525252525252525252525252525252Fexplanation%2525252525252525252525252525252525252525253Fredirect_path%2525252525252525252525252525252525252525253D%252525252525252525252525252525252525252525252Fdatasets%252525252525252525252525252525252525252525252Fregion%252525252525252525252525252525252525252525252F12%252525252525252525252525252525252525252525253Forder_by%252525252525252525252525252525252525252525253Dalpha%2525252525252525252525252525252525252525252526page%252525252525252525252525252525252525252525253D3","url":"https://transport.data.gouv.fr:443/login/explanation"},"server_name":"3794a07a-3e29-4b0e-b179-60fa7c33657e.internal","stacktrace":{"frames":[{"context_line":null,"filename":"lib/phoenix/router.ex","function":"Phoenix.Router.__call__/2","in_app":false,"lineno":288,"module":"Elixir.Phoenix.Router","post_context":[],"pre_context":[],"vars":{}}
2020-11-12T09:20:01+01:00 08:20:00.990 request_id=Fka04j1q2zhCHLwAAMui [info] GET /login/explanation
2020-11-12T09:20:01+01:00 08:20:00.991 request_id=Fka04j1q2zhCHLwAAMui [info] Sent 200 in 923µs
2020-11-12T09:20:02+01:00 Event ID: 93b7b493a87a4dca99bff85216ab4663 - "Received 403 from Sentry server: Event dropped due to filter"
2020-11-12T09:20:02+01:00 08:20:02.039 [warn] Failed to send Sentry event.

**Comment by thbar** [comment]
Après enquête il s'avère que l'application crashe, probablement car il n'y a plus assez de mémoire.

### Post mortem

Ce qui a mis la puce à l'oreille c'est le monitoring mis en place par @fchabouis, qui donne une trace des moments où le site était indisponible (https://status.transport.data.gouv.fr/786046996):

<img width="797" alt="CleanShot 2020-11-26 at 10 53 26@2x" src="https://user-images.githubusercontent.com/10141/100335752-9fc59e00-2fd5-11eb-8b1f-d3d9351eeceb.png">

On voit que le site est down vers 8h30 GMT+1 (soit 7h30 UTC).

Après vérification le serveur tourne en UTC (vérifié à l'aide de `clever ssh`).

@antoine-de m'a montré que le code d'import tournait en début de matinée à 7AM UTC:

https://github.com/etalab/transport-site/blob/1a3f3a0615e5e942976364b4f4d95e5e95806fa4/config/prod.exs#L13-L16

Cet import est constitué de deux phases: import puis validation:

https://github.com/etalab/transport-site/blob/1a3f3a0615e5e942976364b4f4d95e5e95806fa4/apps/transport/lib/transport/import_data.ex#L64-L68

En greppant sur les logs on voit bien que l'import fonctionne et se termine:

```
$ clever logs --alias transport-site --search reimporting
Waiting for application logs…
2020-11-24T07:00:00.385Z: 07:00:00.001 [info] reimporting all datasets
2020-11-25T07:00:00.172Z: 07:00:00.001 [info] reimporting all datasets
2020-11-26T07:00:00.393Z: 07:00:00.001 [info] reimporting all datasets

$ clever logs --alias transport-site --search reimported
Waiting for application logs…
2020-11-24T07:30:03.220Z: 07:30:03.063 [info] all datasets have been reimported (59 failures / 414)
2020-11-25T07:31:15.812Z: 07:31:15.507 [info] all datasets have been reimported (60 failures / 415)
2020-11-26T07:29:12.485Z: 07:29:11.955 [info] all datasets have been reimported (59 failures / 415)
```

Tout cela se termine un peu avant le fameux crash.

La suite tend à montrer que la partie validation commence, mais ne termine pas:

```
$ clever logs --alias transport-site --search Validating | grep "all"
2020-11-24T07:30:03.220Z: 07:30:03.063 [info] Validating all resources
2020-11-25T07:31:15.812Z: 07:31:15.507 [info] Validating all resources
2020-11-26T07:29:12.485Z: 07:29:11.955 [info] Validating all resources

$ clever logs --alias transport-site --search launching
Waiting for application logs…
# NOTHING
```

On voit que CleverCloud semble redémarrer automatiquement l'application juste à ce moment là:



Et effectivement, dans les derniers logs du déploiement précédent on voit:

```
2020-11-26T08:29:16+01:00 07:29:15.854 request_id=Fkr-PS9hYu3rOZUAEHph [info] Sent 200 in 1ms
2020-11-26T08:29:19+01:00 time="2020-11-26T07:29:19.369526550Z" level=info msg="shim reaped" id=611ee087054ae4a69578d67da4a6d237c9190083b79ca3a4f53e5edcab149987
2020-11-26T08:29:19+01:00 Failed with reason 'Failed executing run'
2020-11-26T08:29:19+01:00 time="2020-11-26T07:29:19.372536060Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
```

La réponse est très probablement un "out of memory error" lié au chargement de toutes les ressources en RAM (plutôt que de streamer) ici:

https://github.com/etalab/transport-site/blob/1a3f3a0615e5e942976364b4f4d95e5e95806fa4/apps/transport/lib/transport/import_data.ex#L40-L44

### Améliorations en cours

- [ ] Modification du code pour ne plus tout charger (@antoine-de)
- [ ] Job à caler plus tôt dans la nuit aussi (@antoine-de)
- [ ] Mise en place NewRelic pour voir si on y voit plus clair (@thbar)

**Comment by thbar** [comment]
La PR #1387 corrige l'import qui faisait un eager-loading de toutes les ressources et validations.

Du coup ça a clairement corrigé:

![CleanShot 2020-12-07 at 09 46 00@2x](https://user-images.githubusercontent.com/10141/101332548-bab9cd00-3875-11eb-8d23-5cfeed50be84.png)

Je clôture
