### ISSUE TITLE
Erreur "Failure while translating Erlang's logger event" durant les tests

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1375]
J'ai vu de temps en temps en travaillant sur des tests l'erreur suivante:

```
10:57:17.761 [info] Failure while translating Erlang's logger event
** (UndefinedFunctionError) function Support.Logger.Translator.translate/4 is undefined (module Support.Logger.Translator is not available)
    Support.Logger.Translator.translate(:info, :info, :report, {{:supervisor, :progress}, [supervisor: {:local, Logger.BackendSupervisor}, started: [pid: #PID<0.348.0>, id: Logger.Backends.Console, mfargs: {Logger.Watcher, :start_link, [{Logger, Logger.Backends.Console, :console}]}, restart_type: :transient, shutdown: 5000, child_type: :worker]]})
    (logger) lib/logger/erlang_handler.ex:104: Logger.ErlangHandler.translate/6
    (logger) lib/logger/erlang_handler.ex:97: Logger.ErlangHandler.translate/5
    (logger) lib/logger/erlang_handler.ex:27: anonymous fn/3 in Logger.ErlangHandler.log/2
    (logger) lib/logger.ex:867: Logger.normalize_message/2
    (logger) lib/logger.ex:690: Logger.__do_log__/3
    (kernel) logger_backend.erl:51: :logger_backend.call_handlers/3
    (kernel) logger_backend.erl:38: :logger_backend.log_allowed/2
    (stdlib) supervisor.erl:368: :supervisor.do_start_child/2
    (stdlib) supervisor.erl:671: :supervisor.handle_start_child/2
    (stdlib) supervisor.erl:420: :supervisor.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

Je n'ai pas encore creusé, ça pourrait être corrigé par #1363, à vérifier mais je note.

### Liens potentiellement utiles

* https://elixirforum.com/t/call-for-testers-new-elixir-logger-backend/26507

**Comment by thbar** [comment]
Ok en fouillant durant #1457 j'ai remarqué ça:

https://github.com/etalab/transport-site/commit/d3e3419a8384d33064bdb7667ccdcc8efab0fc86

Il va simplement falloir reprendre la configuration du logger et la mettre à plat (en n'oubliant pas de conserver Sentry).

**Comment by thbar** [comment]
Réglé via #1547.
