### ISSUE TITLE
cookie named "_transport_key" exceeds maximum size of 4096 bytes

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1476]
Je vois régulièrement ce message dans les logs.

Ca ressemble à une boucle de redirection infinie, peut-être un retour de #117.

```
2021-01-28T11:36:37.222Z:    ** (Plug.Conn.CookieOverflowError) cookie named "_transport_key" exceeds maximum size of 4096 bytes
2021-01-28T11:36:37.223Z:        (phoenix 1.4.17) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
2021-01-28T11:36:37.222Z: 11:36:36.759 [error] #PID<0.30115.2> running TransportWeb.Endpoint (cowboy_protocol) terminated
2021-01-28T11:36:37.223Z:        (transport 0.0.1) lib/transport_web/controllers/page_controller.ex:1: TransportWeb.PageController.action/2
2021-01-28T11:36:37.222Z: Request: GET /login/explanation?redirect_path=%2Flogin%2Fexplanation%3Fredirect_path%3D%252Flogin%252Fexplanation%253Fredirect_path%253D%25252Flogin%25252Fexplanation%25253Fredirect_path%25253D%2525252Flogin%2525252Fexplanation%2525253Fredirect_path%2525253D%252525252Flogin%252525252Fexplanation%252525253Fredirect_path%252525253D%25252525252Flogin%25252525252Fexplanation%25252525253Fredirect_path%25252525253D%2525252525252Flogin%2525252525252Fexplanation%2525252525253Fredirect_path%2525252525253D%252525252525252Flogin%252525252525252Fexplanation%252525252525253Fredirect_path%252525252525253D%25252525252525252Flogin%25252525252525252Fexplanation%25252525252525253Fredirect_path%25252525252525253D%2525252525252525252Flogin%2525252525252525252Fexplanation%2525252525252525253Fredirect_path%2525252525252525253D%252525252525252525252Flogin%252525252525252525252Fexplanation%252525252525252525253Fredirect_path%252525252525252525253D%25252525252525252525252Flogin%25252525252525252525252Fexplanation%25252525252525252525253Fredirect_path%25252525252525252525253D%2525252525252525252525252Flogin%2525252525252525252525252Fexplanation%2525252525252525252525253Fredirect_path%2525252525252525252525253D%252525252525252525252525252Flogin%252525252525252525252525252Fexplanation%252525252525252525252525253Fredirect_path%252525252525252525252525253D%25252525252525252525252525252Flogin%25252525252525252525252525252Fexplanation%25252525252525252525252525253Fredirect_path%25252525252525252525252525253D%2525252525252525252525252525252Flogin%2525252525252525252525252525252Fexplanation%2525252525252525252525252525253Fredirect_path%2525252525252525252525252525253D%252525252525252525252525252525252Flogin%252525252525252525252525252525252Fexplanation%252525252525252525252525252525253Fredirect_path%252525252525252525252525252525253D%25252525252525252525252525252525252Flogin%25252525252525252525252525252525252Fexplanation%25252525252525252525252525252525253Fredirect_path%25252525252525252525252525252525253D%2525252525252525252525252525252525252Flogin%2525252525252525252525252525252525252Fexplanation%2525252525252525252525252525252525253Fredirect_path%2525252525252525252525252525252525253D%252525252525252525252525252525252525252Flogin%252525252525252525252525252525252525252Fexplanation%252525252525252525252525252525252525253Fredirect_path%252525252525252525252525252525252525253D%25252525252525252525252525252525252525252Flogin%25252525252525252525252525252525252525252Fexplanation%25252525252525252525252525252525252525253Fredirect_path%25252525252525252525252525252525252525253D%2525252525252525252525252525252525252525252Flogin%2525252525252525252525252525252525252525252Fexplanation%2525252525252525252525252525252525252525253Fredirect_path%2525252525252525252525252525252525252525253D%252525252525252525252525252525252525252525252Flogin%252525252525252525252525252525252525252525252Fexplanation%252525252525252525252525252525252525252525253Fredirect_path%252525252525252525252525252525252525252525253D%25252525252525252525252525252525252525252525252Flogin%25252525252525252525252525252525252525252525252Fexplanation%25252525252525252525252525252525252525252525253Fredirect_path%25252525252525252525252525252525252525252525253D%2525252525252525252525252525252525252525252525252Fdatasets%2525252525252525252525252525252525252525252525253Ffilter%2525252525252525252525252525252525252525252525253Dhas_realtime%25252525252525252525252525252525252525252525252526page%2525252525252525252525252525252525252525252525253D21
2021-01-28T11:36:37.222Z: ** (exit) an exception was raised:
2021-01-28T11:36:37.223Z:        (transport 0.0.1) lib/transport_web/controllers/page_controller.ex:1: TransportWeb.PageController.phoenix_controller_pipeline/2
2021-01-28T11:36:37.223Z:        (stdlib 3.12.1) maps.erl:232: :maps.fold_1/3
```

**Comment by thbar** [comment]
J'ai remarqué que ça semble venir toujours de la même IP. J'ai contacté le support Clever mais je n'ai pas encore l'explication.

Ca pourrait être un outil de monitoring.

**Comment by thbar** [comment]
Après la mise à jour Sentry (#1547) je vois que cette erreur semble toujours liée à SemrushBot. Je vais dans un premier temps notifier qu'il faut arrêter via `robots.txt`.

**Comment by thbar** [comment]
Le fix a l'air de régler le souci pour l'instant, je ferme.
