### ISSUE TITLE
Echecs des tests navigateur

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1504]
En travaillant sur #1457 certains tests échouent. Je crée un ticket séparément car il y a un peu trop d'information.

Je ne sais pas encore si c'est lié à la version de ChromeDriver (a priori non, car j'ai la même en local, mais je suis sur mac, il faudrait tester sur linux), ou à un changement dans Hound, ou autre.

Exemple d'occurrence du problème (build https://app.circleci.com/pipelines/github/etalab/transport-site/1214/workflows/3eca7a7b-7b8d-466d-941d-b50de33117e8).

À chaque fois l'erreur est `Unable to determine element locating strategy for class name`.

### test_integration

[link](https://app.circleci.com/pipelines/github/etalab/transport-site/1214/workflows/3eca7a7b-7b8d-466d-941d-b50de33117e8/jobs/24000)

```
#!/bin/bash -eo pipefail
export SECRET_KEY_BASE=`mix phx.gen.secret`
mix test --only integration

# SNIP

==> transport
Excluding tags: [:test, :solution, :external, :pending]
Including tags: [:integration]

warning: Transport.ReusableData.create_dataset/1 is undefined (module Transport.ReusableData is not available or is yet to be defined)
  test/transport_web/solutions/data_reuse/using_map_test.exs:21: TransportWeb.Solution.DataReuse.UsingMapTest.__ex_unit_setup_all_3/1



  1) test add a button to contact the team and ask for help (TransportWeb.Integration.ContactTest)
     apps/transport/test/transport_web/integrations/contact_test.exs:7
     ** (Hound.Error) could not get element {:class, "mail__button"}: "Unable to determine element locating strategy for class name"
     code: |> find_element("mail__button")
     stacktrace:
       (hound 1.1.1) lib/hound/helpers/page.ex:53: Hound.Helpers.Page.find_element/3
       test/transport_web/integrations/contact_test.exs:13: (test)



  2) test I can list available datasets to find and download transport data (TransportWeb.Solution.DataReuse.UsingListTest)
     apps/transport/test/transport_web/solutions/data_reuse/using_list_test.exs:67
     ** (Hound.Error) could not get element {:class, "download-button"}: "Unable to determine element locating strategy for class name"
     code: |> find_element("download-button")
     stacktrace:
       (hound 1.1.1) lib/hound/helpers/page.ex:53: Hound.Helpers.Page.find_element/3
       test/transport_web/solutions/data_reuse/using_list_test.exs:88: (test)

.

  3) test deny acces to backoffice if not logged (TransportWeb.Integration.BackofficeTest)
     apps/transport/test/transport_web/integrations/backoffice_test.exs:8
     ** (Hound.Error) could not get element {:class, "notification"}: "Unable to determine element locating strategy for class name"
     code: |> find_element("notification")
     stacktrace:
       (hound 1.1.1) lib/hound/helpers/page.ex:53: Hound.Helpers.Page.find_element/3
       test/transport_web/integrations/backoffice_test.exs:14: (test)

..

Finished in 21.0 seconds
46 doctests, 64 tests, 3 failures, 104 excluded

Randomized with seed 544249

Exited with code exit status 1
CircleCI received exit code 1
```

### test_solution

[link](https://app.circleci.com/pipelines/github/etalab/transport-site/1214/workflows/3eca7a7b-7b8d-466d-941d-b50de33117e8/jobs/23995)

```
#!/bin/bash -eo pipefail
export SECRET_KEY_BASE=`mix phx.gen.secret`
mix test --only solution

# SNIP

==> transport
Excluding tags: [:test, :integration, :external, :pending]
Including tags: [:solution]

warning: Transport.ReusableData.create_dataset/1 is undefined (module Transport.ReusableData is not available or is yet to be defined)
  test/transport_web/solutions/data_reuse/using_map_test.exs:21: TransportWeb.Solution.DataReuse.UsingMapTest.__ex_unit_setup_all_3/1



  1) test I can see a log in link (TransportWeb.Solution.LoginTest)
     apps/transport/test/transport_web/solutions/login_test.exs:17
     ** (Hound.Error) could not get element {:class, "navigation__link--login"}: "Unable to determine element locating strategy for class name"
     code: click({:class, "navigation__link--login"})
     stacktrace:
       (hound 1.1.1) lib/hound/helpers/page.ex:53: Hound.Helpers.Page.find_element/3
       (hound 1.1.1) lib/hound/helpers/element.ex:289: Hound.Helpers.Element.click/1
       test/transport_web/solutions/login_test.exs:23: (test)



Finished in 7.2 seconds
46 doctests, 64 tests, 1 failure, 109 excluded

Randomized with seed 968270

Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by thbar** [comment]
@fchabouis vu que tu n'es pas sur mac, ça serait top qu'on vérifie si l'erreur est reproductible chez toi, ça facilitera le déboggage.

**Comment by thbar** [comment]
Le fix supposé ne fonctionne pas.

**Comment by fchabouis** [comment]
Nous avons résolut le problème temporairement en passant à chromedriver 86 via [45e468](https://github.com/etalab/transport-site/pull/1457/commits/12aae6d88260c3372da6c6a92da828ff1a45e468). Il faudra essayer de comprendre pourquoi.
