### ISSUE TITLE
Régression sur un test unitaire

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1613]
Suite à la dernière PR #1612 je constate une régression mais qui porte à première vue uniquement sur les tests, et que je ne reproduis pas en local sur Mac:

https://app.circleci.com/pipelines/github/etalab/transport-site/1476/workflows/c928d4e9-e1f6-4e86-8cc0-eab4e48eb2a1/jobs/25575

```
  1) doctest Opendatasoft.UrlExtractor.get_resources_with_url_from_csv/1 (6) (Transport.UrlExtractorDocTest)
     apps/transport/test/transport/url_extractor_doc_test.exs:4
     ** (UndefinedFunctionError) function HTTPoison.head/1 is undefined or private, but the behaviour HTTPoison.Base expects it to be present
     stacktrace:
       (httpoison 1.8.0) HTTPoison.head("http")
       (transport 0.0.1) lib/opendatasoft/url_extractor.ex:236: Opendatasoft.UrlExtractor.get_filename/1
       (transport 0.0.1) lib/opendatasoft/url_extractor.ex:131: anonymous fn/2 in Opendatasoft.UrlExtractor.get_resources_with_url_from_csv/1
       (elixir 1.10.4) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
       (transport 0.0.1) lib/opendatasoft/url_extractor.ex:124: Opendatasoft.UrlExtractor.get_resources_with_url_from_csv/1
       (for doctest at) lib/opendatasoft/url_extractor.ex:113: (test)
```

**Comment by thbar** [comment]
Erreur temporaire. Je me demande si c'est lié au cache #1611. Je clôture pour l'instant.
