### ISSUE TITLE
Erreur temporaire en usage de Mox

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1648]
Aujourd'hui en travaillant sur #1616, j'ai constaté une erreur durant les tests. Elle a disparu dans la foulée, toutefois je la trace ici si jamais elle revient, car ce n'est pas normal:

```
1) test Fetcher.S3 history_resources (regular use) (Transport.HistoryTest)
     apps/transport/test/transport/history_test.exs:83
     ** (exit) exited in: GenServer.call(Mox.Server, {:verify_on_exit, #PID<0.3019.0>}, 30000)
         ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
     stacktrace:
       (elixir 1.10.4) lib/gen_server.ex:1013: GenServer.call/3
       lib/mox.ex:658: Mox.verify_on_exit!/1
       test/transport/history_test.exs:1: Transport.HistoryTest.__ex_unit__/2



  2) test backup_resources (Transport.HistoryTest)
     apps/transport/test/transport/history_test.exs:13
     ** (exit) exited in: GenServer.call(Mox.Server, {:verify_on_exit, #PID<0.3022.0>}, 30000)
         ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
     stacktrace:
       (elixir 1.10.4) lib/gen_server.ex:1013: GenServer.call/3
       lib/mox.ex:658: Mox.verify_on_exit!/1
       test/transport/history_test.exs:1: Transport.HistoryTest.__ex_unit__/2



  3) test Fetcher.S3 history_resources (no bucket found) (Transport.HistoryTest)
     apps/transport/test/transport/history_test.exs:81
     ** (exit) exited in: GenServer.call(Mox.Server, {:verify_on_exit, #PID<0.3024.0>}, 30000)
         ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
     stacktrace:
       (elixir 1.10.4) lib/gen_server.ex:1013: GenServer.call/3
       lib/mox.ex:658: Mox.verify_on_exit!/1
       test/transport/history_test.exs:1: Transport.HistoryTest.__ex_unit__/2

```

**Comment by thbar** [comment]
Cela ne s'est produit qu'une fois, je clôture pour l'instant.
