### ISSUE TITLE
Incompatibilité avec Ecto 3.6.2 à corriger

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1718]
Rien de bloquant à ce stade, je documente ce dont j'ai pris conscience en tentant des petites mises à jour suite à #1717.

L'application utilise actuellement Ecto 3.6.1. 

Si on passe sur [3.6.2](https://github.com/elixir-ecto/ecto/blob/master/CHANGELOG.md#v362-2021-05-28), on incorpore le bugfix suivant:

> [Ecto.Query] Raise if a nil value is given to a query from a nested map parameter

Cela déclenche des erreurs dans les tests, et je ne sais pas encore si cela a un impact également "dans la vraie vie" ou pas.

Voici les erreurs en question:

```
==> transport
Excluding tags: [:external, :pending]

...............................10:51:42.031 [warn] Cannot process nil url (url) at the moment. Skipping.
.....................................................

  1) test GET /datasets/aom/4242  (TransportWeb.SeoMetadataTest)
     apps/transport/test/transport_web/controllers/seo_test.exs:64
     ** (ArgumentError) comparison with nil is forbidden as it is unsafe. If you want to check if a value is nil, use is_nil/1 instead
     code: title = conn |> get("/datasets/aom/4242") |> html_response(200) |> title
     stacktrace:
       (ecto 3.6.2) lib/ecto/query/builder.ex:928: Ecto.Query.Builder.not_nil!/1
       (db 0.1.0) lib/db/dataset.ex:175: DB.Dataset.filter_by_aom/2
       (db 0.1.0) lib/db/dataset.ex:245: DB.Dataset.list_datasets/1
       (transport 0.0.1) lib/transport_web/controllers/dataset_controller.ex:119: TransportWeb.DatasetController.get_datasets/1
       (transport 0.0.1) lib/transport_web/controllers/dataset_controller.ex:22: TransportWeb.DatasetController.list_datasets/3
       (transport 0.0.1) lib/transport_web/controllers/dataset_controller.ex:99: TransportWeb.DatasetController.by_territory/5
       (transport 0.0.1) lib/transport_web/controllers/dataset_controller.ex:1: TransportWeb.DatasetController.action/2
       (transport 0.0.1) lib/transport_web/controllers/dataset_controller.ex:1: TransportWeb.DatasetController.phoenix_controller_pipeline/2
       (phoenix 1.5.8) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
       (transport 0.0.1) lib/transport_web/router.ex:1: TransportWeb.Router.call/2
       (transport 0.0.1) lib/plug/router.ex:284: TransportWeb.Plugs.Router.dispatch/2
       (transport 0.0.1) lib/transport_web/plugs/router.ex:1: TransportWeb.Plugs.Router.plug_builder_call/2
       (transport 0.0.1) lib/transport_web/endpoint.ex:1: TransportWeb.Endpoint.plug_builder_call/2
       (transport 0.0.1) lib/transport_web/endpoint.ex:1: TransportWeb.Endpoint."call (overridable 3)"/2
       (transport 0.0.1) lib/transport_web/endpoint.ex:1: TransportWeb.Endpoint.call/2
       (phoenix 1.5.8) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/transport_web/controllers/seo_test.exs:65: (test)

............

  2) test GET /datasets/aom/4242 (TransportWeb.DatasetSearchControllerTest)
     apps/transport/test/transport_web/controllers/dataset_search_test.exs:85
     ** (ArgumentError) comparison with nil is forbidden as it is unsafe. If you want to check if a value is nil, use is_nil/1 instead
     code: conn = conn |> get(dataset_path(conn, :by_aom, 4242))
     stacktrace:
       (ecto 3.6.2) lib/ecto/query/builder.ex:928: Ecto.Query.Builder.not_nil!/1
       (db 0.1.0) lib/db/dataset.ex:175: DB.Dataset.filter_by_aom/2
       (db 0.1.0) lib/db/dataset.ex:245: DB.Dataset.list_datasets/1
       (transport 0.0.1) lib/transport_web/controllers/dataset_controller.ex:119: TransportWeb.DatasetController.get_datasets/1
       (transport 0.0.1) lib/transport_web/controllers/dataset_controller.ex:22: TransportWeb.DatasetController.list_datasets/3
       (transport 0.0.1) lib/transport_web/controllers/dataset_controller.ex:99: TransportWeb.DatasetController.by_territory/5
       (transport 0.0.1) lib/transport_web/controllers/dataset_controller.ex:1: TransportWeb.DatasetController.action/2
       (transport 0.0.1) lib/transport_web/controllers/dataset_controller.ex:1: TransportWeb.DatasetController.phoenix_controller_pipeline/2
       (phoenix 1.5.8) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
       (transport 0.0.1) lib/transport_web/router.ex:1: TransportWeb.Router.call/2
       (transport 0.0.1) lib/plug/router.ex:284: TransportWeb.Plugs.Router.dispatch/2
       (transport 0.0.1) lib/transport_web/plugs/router.ex:1: TransportWeb.Plugs.Router.plug_builder_call/2
       (transport 0.0.1) lib/transport_web/endpoint.ex:1: TransportWeb.Endpoint.plug_builder_call/2
       (transport 0.0.1) lib/transport_web/endpoint.ex:1: TransportWeb.Endpoint."call (overridable 3)"/2
       (transport 0.0.1) lib/transport_web/endpoint.ex:1: TransportWeb.Endpoint.call/2
       (phoenix 1.5.8) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/transport_web/controllers/dataset_search_test.exs:86: (test)
```

**Comment by fchabouis** [comment]
fermé avec #1821
