### ISSUE TITLE
Tests qui échouent du fait de l'absence de gtfs-to-geosjon

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1820]
### Tâches en cours

En premier lieu, on va:
- [x] Créer un hotfix qui va juste bypasser ces tests lorsqu'on n'est pas en CI -> voir #1822

Toutefois, c'est reculer pour mieux sauter, car on va avoir besoin de:
- Par défaut, exclure en local ces tests qui nécessitent un setup un peu particulier (de façon safe)
- Permettre de les activer automatiquement au cas par cas en local, avec un chemin custom pour chaque convertisseur (pour pouvoir travailler avec des versions compilées localement, ce qui aura une grosse utilité, ou même en appelant directement Docker avec la bonne ligne de commande)
- Lever une erreur dans tous les cas sur le CI si les binaires ne répondent pas (être sûr de lancer ces tests en CI)

- [ ] Donc on conservera ce ticket ouvert pour traiter les besoins ci-dessus
 
### Contexte d'origine

Depuis #1802, il y a des tests qui servent à vérifier que le lancement du convertisseur via la CLI fonctionne.

Ces tests passent sur le CI, car l'image Docker utilisée comprend le binaire qui est attendu.

Voici les tests qui échouent:

```
1) test test the gtfs to geojson conversion check the conversion binary is accessible (TransportWeb.GeojsonConversionControllerTest)
     apps/transport/test/transport_web/controllers/geojson_conversion_controller_test.exs:7
     Assertion with != failed, both sides are exactly equal
     code: assert msg != "rambo exited with 0"
     left: "rambo exited with 0"
     stacktrace:
       test/transport_web/controllers/geojson_conversion_controller_test.exs:11: (test)

  2) test test the gtfs to geojson conversion we can convert a gtfs (TransportWeb.GeojsonConversionControllerTest)
     apps/transport/test/transport_web/controllers/geojson_conversion_controller_test.exs:14
     ** (MatchError) no match of right hand side value: {:error, "rambo exited with 0"}
     code: {:ok, msg} = GeojsonConversionController.call_geojson_converter("#{__DIR__}/../../fixture/files/gtfs.zip")
     stacktrace:
       test/transport_web/controllers/geojson_conversion_controller_test.exs:15: (test)
```

Je prends le ticket en main pour voir quelle est la meilleure solution.

**Comment by thbar** [comment]
Déjà je n'ai pas tout à fait les mêmes résultats en local (je note ça non pas pour réfuter le point, mais pour considérer les variantes). J'ai un échec et une réussite (mais je pense que c'est lié à la façon dont est écrit le test potentiellement):

```
❯ mix cmd --app transport mix test --only focus --color 

15:33:13.244 [warn]  Only the most basic features will work. Please create /Users/thbar/git/transport/transport-site/config/dev.secret.exs based on config/dev.secret.template.exs for more advanced use.
==> transport
Excluding tags: [:test, :pending]
Including tags: [:focus]

sh: /Users/thbar/git/transport/transport-site/_build/test/lib/rambo/priv/rambo: No such file or directory
sh: line 0: exec: /Users/thbar/git/transport/transport-site/_build/test/lib/rambo/priv/rambo: cannot execute: No such file or directory
.sh: /Users/thbar/git/transport/transport-site/_build/test/lib/rambo/priv/rambo: No such file or directory
sh: line 0: exec: /Users/thbar/git/transport/transport-site/_build/test/lib/rambo/priv/rambo: cannot execute: No such file or directory


  1) test test the gtfs to geojson conversion we can convert a gtfs (TransportWeb.GeojsonConversionControllerTest)
     test/transport_web/controllers/geojson_conversion_controller_test.exs:16
     ** (MatchError) no match of right hand side value: {:error, "rambo exited with 126"}
     code: {:ok, msg} = GeojsonConversionController.call_geojson_converter("#{__DIR__}/../../fixture/files/gtfs.zip")
     stacktrace:
       test/transport_web/controllers/geojson_conversion_controller_test.exs:17: (test)



Finished in 0.6 seconds (0.6s async, 0.01s sync)
49 doctests, 107 tests, 1 failure, 154 excluded

Randomized with seed 989500
** (exit) 1
    (mix 1.12.2) lib/mix/tasks/cmd.ex:64: Mix.Tasks.Cmd.run/1
    (mix 1.12.2) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.2) lib/mix/project.ex:353: Mix.Project.in_project/4
    (elixir 1.12.2) lib/file.ex:1560: File.cd!/2
    (mix 1.12.2) lib/mix/task.ex:520: anonymous fn/4 in Mix.Task.recur/1
    (elixir 1.12.2) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.12.2) lib/mix/task.ex:519: Mix.Task.recur/1
    (mix 1.12.2) lib/mix/project_stack.ex:181: Mix.ProjectStack.recur/1
```

**Comment by AntoineAugusti** [comment]
Géré depuis, avec l'ajout d'un tag il me semble.
