### ISSUE TITLE
Quand data.gouv.fr est down les pages dataset sont en erreur 500

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#1842]
On l'avait corrigé déjà lors de l'incendie de Strasbourg, mais visiblement le problème est revenu !

Les logs sur prochainement :

```
 2021-10-13T10:04:43+02:00 ** (FunctionClauseError) no function clause matching in Datagouvfr.Client.API.decode_body/1
2021-10-13T10:04:43+02:00 (datagouvfr 0.1.0) lib/datagouvfr/client/api.ex:19: Datagouvfr.Client.API.decode_body({:error, %HTTPoison.Error{id: nil, reason: :timeout}})
2021-10-13T10:04:43+02:00 (datagouvfr 0.1.0) lib/datagouvfr/client/api.ex:90: Datagouvfr.Client.API.request_url/5
2021-10-13T10:04:43+02:00 (datagouvfr 0.1.0) lib/datagouvfr/client/reuses.ex:12: Datagouvfr.Client.Reuses.get/1
2021-10-13T10:04:43+02:00 (transport 0.0.1) lib/transport_web/controllers/dataset_controller.ex:39: TransportWeb.DatasetController.details/2
2021-10-13T10:04:43+02:00 (transport 0.0.1) lib/transport_web/controllers/dataset_controller.ex:1: TransportWeb.DatasetController.action/2
2021-10-13T10:04:43+02:00 (transport 0.0.1) lib/transport_web/controllers/dataset_controller.ex:1: 
```

**Comment by AntoineAugusti** [comment]
> Called with 1 arguments
{:error, %HTTPoison.Error{id: nil, reason: :timeout}}

> Attempted function clauses (showing 2 out of 2)
def decode_body({:ok, %HTTPoison.Response{body: "", status_code: status_code}})
def decode_body({:ok, %HTTPoison.Response{body: body, status_code: status_code}}) when is_binary(body)

**Comment by AntoineAugusti** [comment]
@fchabouis Je prends l'issue si ça te dérange pas

**Comment by thbar** [comment]
Suggestion : hot-fix, mais derrière une approche systématique où cette page est mise sous tests "mode dégradé", je crois qu'il est temps !
