### ISSUE TITLE
La mise à jour de Finch casse des tests

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2314]
Découvert dans #2307, en tentant la mise à jour suivante:

https://diff.hex.pm/diff/finch/0.10.2..0.11.0

J'ai les "failures" suivantes. Je crée un ticket à part pour ne pas bloquer le déploiement de #2307.

```
❯ mix test apps/shared/test/http_stream_v2_test.exs 

08:08:22.223 [info]  Migrations already up
==> shared
warning: redefining module Transport.HTTPoison.Mock (current version loaded from /Users/thbar/git/transport/transport-site/_build/test/lib/transport/ebin/Elixir.Transport.HTTPoison.Mock.beam)
  /Users/thbar/git/transport/transport-site/deps/mox/lib/mox.ex:443



  1) test streams the content and compute expected information after a redirect (HTTPStreamV2.Test)
     apps/shared/test/http_stream_v2_test.exs:30
     ** (CaseClauseError) no case clause matching: {:ok, %Mint.HTTP1{buffer: "", host: "localhost", mode: :passive, port: 64734, private: %{}, proxy_headers: [], request: nil, requests: {[], []}, scheme_as_string: "http", socket: #Port<0.31>, state: :open, streaming_request: nil, transport: Mint.Core.Transport.TCP}, %{body_byte_size: 11, hash: #Reference<0.1190707009.2022572034.164271>, headers: [{"cache-control", "max-age=0, private, must-revalidate"}, {"content-length", "11"}, {"date", "Tue, 12 Apr 2022 06:08:22 GMT"}, {"hello", "header"}, {"server", "Cowboy"}], status: 200}}
     code: {:ok, result} = HTTPStreamV2.fetch_status_and_hash(url)
     stacktrace:
       (finch 0.11.0) lib/finch/http1/conn.ex:178: Finch.Conn.handle_response/5
       (finch 0.11.0) lib/finch/http1/conn.ex:122: Finch.Conn.request/6
       (finch 0.11.0) lib/finch/http1/pool.ex:50: anonymous fn/8 in Finch.HTTP1.Pool.request/5
       (nimble_pool 0.2.6) lib/nimble_pool.ex:349: NimblePool.checkout!/4
       (finch 0.11.0) lib/finch/http1/pool.ex:43: Finch.HTTP1.Pool.request/5
       (shared 0.1.0) lib/http_stream_v2.ex:40: HTTPStreamV2.fetch_status_and_hash/3
       test/http_stream_v2_test.exs:52: (test)



  2) test streams the content and compute expected information (HTTPStreamV2.Test)
     apps/shared/test/http_stream_v2_test.exs:9
     ** (CaseClauseError) no case clause matching: {:ok, %Mint.HTTP1{buffer: "", host: "localhost", mode: :passive, port: 64738, private: %{}, proxy_headers: [], request: nil, requests: {[], []}, scheme_as_string: "http", socket: #Port<0.35>, state: :open, streaming_request: nil, transport: Mint.Core.Transport.TCP}, %{body_byte_size: 17, hash: #Reference<0.1190707009.2022572036.171330>, headers: [{"cache-control", "max-age=0, private, must-revalidate"}, {"content-length", "17"}, {"date", "Tue, 12 Apr 2022 06:08:22 GMT"}, {"hello", "header"}, {"server", "Cowboy"}], status: 200}}
     code: {:ok, result} = HTTPStreamV2.fetch_status_and_hash(url)
     stacktrace:
       (finch 0.11.0) lib/finch/http1/conn.ex:178: Finch.Conn.handle_response/5
       (finch 0.11.0) lib/finch/http1/conn.ex:122: Finch.Conn.request/6
       (finch 0.11.0) lib/finch/http1/pool.ex:50: anonymous fn/8 in Finch.HTTP1.Pool.request/5
       (nimble_pool 0.2.6) lib/nimble_pool.ex:349: NimblePool.checkout!/4
       (finch 0.11.0) lib/finch/http1/pool.ex:43: Finch.HTTP1.Pool.request/5
       (shared 0.1.0) lib/http_stream_v2.ex:40: HTTPStreamV2.fetch_status_and_hash/3
       test/http_stream_v2_test.exs:17: (test)

..

  3) test hashing works with url containing caracaters that need to be encoded (HTTPStreamV2.Test)
     apps/shared/test/http_stream_v2_test.exs:68
     ** (CaseClauseError) no case clause matching: {:ok, %Mint.HTTP1{buffer: "", host: "localhost", mode: :passive, port: 64746, private: %{}, proxy_headers: [], request: nil, requests: {[], []}, scheme_as_string: "http", socket: #Port<0.51>, state: :open, streaming_request: nil, transport: Mint.Core.Transport.TCP}, %{body_byte_size: 15, hash: #Reference<0.1190707009.2022572036.171430>, headers: [{"cache-control", "max-age=0, private, must-revalidate"}, {"content-length", "15"}, {"date", "Tue, 12 Apr 2022 06:08:22 GMT"}, {"server", "Cowboy"}], status: 200}}
     code: {:ok, result} = HTTPStreamV2.fetch_status_and_hash(url)
     stacktrace:
       (finch 0.11.0) lib/finch/http1/conn.ex:178: Finch.Conn.handle_response/5
       (finch 0.11.0) lib/finch/http1/conn.ex:122: Finch.Conn.request/6
       (finch 0.11.0) lib/finch/http1/pool.ex:50: anonymous fn/8 in Finch.HTTP1.Pool.request/5
       (nimble_pool 0.2.6) lib/nimble_pool.ex:349: NimblePool.checkout!/4
       (finch 0.11.0) lib/finch/http1/pool.ex:43: Finch.HTTP1.Pool.request/5
       (shared 0.1.0) lib/http_stream_v2.ex:40: HTTPStreamV2.fetch_status_and_hash/3
       test/http_stream_v2_test.exs:77: (test)

..

Finished in 0.1 seconds (0.1s async, 0.00s sync)
7 tests, 3 failures

Randomized with seed 587569
```

**Comment by thbar** [comment]
Curieux, je n'ai pas retrouvé ce point durant #2416, je vais essayer de voir pourquoi.
