### ISSUE TITLE
Voir backoff pour job SingleGtfsToNetexConverterJob

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2360]
La conversion de GTFS vers NeTEx est une opération gourmande et qui est susceptible de ne jamais réussir si le fichier GTFS est vraiment invalide.

Actuellement ces jobs sont rééssayés au moins toutes les 24h, sans perspective de réussir un jour.

Regarder du côté de backoff de Oban pour étaler les essais dans le temps.

Doc : https://hexdocs.pm/oban/Oban.Worker.html#module-customizing-backoff

**Comment by AntoineAugusti** [comment]
J'ai regardé les erreurs actuelles avec

```sql
select unnest(errors)->>'error', count(1)
from oban_jobs
where worker = 'Transport.Jobs.SingleGtfsToNetexConverterJob' and errors != '{}'
group by 1
```

Et je trouve les comptes suivants, en ayant nettoyé un peu les stacktraces.

|error | count|
|--- | ---|
|** (MatchError) no match of right hand side value: {:error, ""}     (transport 0.0.1) lib/jobs/gtfs_generic_converter.ex:97: Transport.Jobs.GTFSGenericConverter.generate_and_upload_conversion/3     (transport 0.0.1) lib/jobs/gtfs_generic_converter.ex:65: Transport.Jobs.GTFSGenericConverter.perform_single_conversion_job/3     (oban 2.10.1) lib/oban/queue/executor.ex:218: Oban.Queue.Executor.perform_inline/2     (oban 2.10.1) lib/oban/queue/executor.ex:206: Oban.Queue.Executor.perform_inline/2     (oban 2.10.1) lib/oban/queue/executor.ex:82: Oban.Queue.Executor.call/1     (elixir 1.13.3) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2     (elixir 1.13.3) lib/task/supervised.ex:34: Task.Supervised.reply/4     (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3 | 286|
|** (MatchError) no match of right hand side value: {:error, "Cannot calculate validity period because there is no dataset\n"}     (transport 0.0.1) lib/jobs/gtfs_generic_converter.ex:97: Transport.Jobs.GTFSGenericConverter.generate_and_upload_conversion/3     (transport 0.0.1) lib/jobs/gtfs_generic_converter.ex:65: Transport.Jobs.GTFSGenericConverter.perform_single_conversion_job/3     (oban 2.10.1) lib/oban/queue/executor.ex:218: Oban.Queue.Executor.perform_inline/2     (oban 2.10.1) lib/oban/queue/executor.ex:206: Oban.Queue.Executor.perform_inline/2     (oban 2.10.1) lib/oban/queue/executor.ex:82: Oban.Queue.Executor.call/1     (elixir 1.13.3) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2     (elixir 1.13.3) lib/task/supervised.ex:34: Task.Supervised.reply/4     (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3 | 48|
|** (HTTPoison.Error) :closed     (httpoison 1.8.1) lib/httpoison.ex:156: HTTPoison.request!/5     (transport 0.0.1) lib/jobs/gtfs_generic_converter.ex:92: Transport.Jobs.GTFSGenericConverter.generate_and_upload_conversion/3     (transport 0.0.1) lib/jobs/gtfs_generic_converter.ex:65: Transport.Jobs.GTFSGenericConverter.perform_single_conversion_job/3     (oban 2.10.1) lib/oban/queue/executor.ex:218: Oban.Queue.Executor.perform_inline/2     (oban 2.10.1) lib/oban/queue/executor.ex:206: Oban.Queue.Executor.perform_inline/2     (oban 2.10.1) lib/oban/queue/executor.ex:82: Oban.Queue.Executor.call/1     (elixir 1.13.3) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2     (elixir 1.13.3) lib/task/supervised.ex:34: Task.Supervised.reply/4 | 1|

On a également ~310 occurences où l'erreur débute par
```
{:error, "impossible to read zipped gtfs
```

et quelques explications de cette erreur
- `calendar_dates.txt or calendar.txt not found` (154 fois)
- identifier 1 not found while building relation networks_to_lines
- identifier 1 not found while building relation stop_areas_to_stop_points
- identifier 3525322 already exists
- the last stop time of the vj '265390007:1' has no departure/arrival, the stop_times.txt file is not valid

où vraisemblablement le caractère non valide du GTFS source empêche la génération d'un fichier NeTEx.

---

L'erreur sans détails (raison `""`) est embêtante. Une autre erreur commune (`"Cannot calculate validity period because there is no dataset"` provient [de ce code](https://github.com/hove-io/transit_model/blob/876333ff1bf837b2b059e36848855b4ab280d09d/src/model.rs#L1179-L1195).

Toutes les erreurs comportant `impossible to read zipped gtfs` semble indiquer que le GTFS est trop invalide pour être converti et que l'erreur n'est pas transiente, ce qui indique que ça ne vaut pas le coup de réessayer de convertir.
