### ISSUE TITLE
Erreur intermittente dans les tests

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2539]
En local depuis quelques temps (probablement lié à nos nettoyages), j'ai parfois cette erreur Ecto:

```
     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 362ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
     
       1. Ensuring your database is available and that you can connect to it
       2. Tracking down slow queries and making sure they are running fast enough
       3. Increasing the pool_size (although this increases resource consumption)
       4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
     
     See DBConnection.start_link/2 for more information
```

Quand ça arrive, c'est en assez grand nombre.

<details><summary>Cliquez ici pour le détail</summary>

```
==> transport
Excluding tags: [:pending, :transport_tools]

...................................................................................................................................................................

  1) test the GTFS validator inserts expected data in DB (Transport.Validators.GtfsTransportValidatorTest)
     test/transport/validators/gtfs_transport_validator_test.exs:14
     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 362ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
     
       1. Ensuring your database is available and that you can connect to it
       2. Tracking down slow queries and making sure they are running fast enough
       3. Increasing the pool_size (although this increases resource consumption)
       4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
     
     See DBConnection.start_link/2 for more information
     
     stacktrace:
       (db_connection 2.4.2) lib/db_connection/ownership.ex:96: DBConnection.Ownership.ownership_checkout/2
       (ecto_sql 3.8.2) lib/ecto/adapters/sql/sandbox.ex:499: Ecto.Adapters.SQL.Sandbox.checkout/2
       test/transport/validators/gtfs_transport_validator_test.exs:1: Transport.Validators.GtfsTransportValidatorTest.__ex_unit__/2



  2) test renders avatar (TransportWeb.LayoutViewTest)
     test/transport_web/views/avatar_view_test.exs:18
     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 525ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
     
       1. Ensuring your database is available and that you can connect to it
       2. Tracking down slow queries and making sure they are running fast enough
       3. Increasing the pool_size (although this increases resource consumption)
       4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
     
     See DBConnection.start_link/2 for more information
     
     stacktrace:
       (db_connection 2.4.2) lib/db_connection/ownership.ex:96: DBConnection.Ownership.ownership_checkout/2
       (ecto_sql 3.8.2) lib/ecto/adapters/sql/sandbox.ex:499: Ecto.Adapters.SQL.Sandbox.checkout/2
       test/transport_web/views/avatar_view_test.exs:3: TransportWeb.LayoutViewTest.__ex_unit_setup_2/1
       test/transport_web/views/avatar_view_test.exs:1: TransportWeb.LayoutViewTest.__ex_unit__/2



  3) test resource last content update time last content update time, download_datime not in payload (DB.ResourceTest)
     test/db/resource_test.exs:321
     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 503ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
     
       1. Ensuring your database is available and that you can connect to it
       2. Tracking down slow queries and making sure they are running fast enough
       3. Increasing the pool_size (although this increases resource consumption)
       4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
     
     See DBConnection.start_link/2 for more information
     
     stacktrace:
       (db_connection 2.4.2) lib/db_connection/ownership.ex:96: DBConnection.Ownership.ownership_checkout/2
       (ecto_sql 3.8.2) lib/ecto/adapters/sql/sandbox.ex:499: Ecto.Adapters.SQL.Sandbox.checkout/2
       test/db/resource_test.exs:13: DB.ResourceTest.__ex_unit_setup_1/1
       test/db/resource_test.exs:1: DB.ResourceTest.__ex_unit__/2



  4) test compute_stats (Transport.StatsHandlerTest)
     test/transport/stats_handler_test.exs:11
     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 514ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
     
       1. Ensuring your database is available and that you can connect to it
       2. Tracking down slow queries and making sure they are running fast enough
       3. Increasing the pool_size (although this increases resource consumption)
       4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
     
     See DBConnection.start_link/2 for more information
     
     stacktrace:
       (db_connection 2.4.2) lib/db_connection/ownership.ex:96: DBConnection.Ownership.ownership_checkout/2
       (ecto_sql 3.8.2) lib/ecto/adapters/sql/sandbox.ex:499: Ecto.Adapters.SQL.Sandbox.checkout/2
       test/transport/stats_handler_test.exs:8: Transport.StatsHandlerTest.__ex_unit_setup_0/1
       test/transport/stats_handler_test.exs:1: Transport.StatsHandlerTest.__ex_unit__/2



  5) test date format in atom feed (TransportWeb.AtomControllerTest)
     test/transport_web/controllers/atom_controller_test.exs:56
     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 420ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
     
       1. Ensuring your database is available and that you can connect to it
       2. Tracking down slow queries and making sure they are running fast enough
       3. Increasing the pool_size (although this increases resource consumption)
       4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
     
     See DBConnection.start_link/2 for more information
     
     stacktrace:
       (db_connection 2.4.2) lib/db_connection/ownership.ex:96: DBConnection.Ownership.ownership_checkout/2
       (ecto_sql 3.8.2) lib/ecto/adapters/sql/sandbox.ex:499: Ecto.Adapters.SQL.Sandbox.checkout/2
       test/transport_web/controllers/atom_controller_test.exs:9: TransportWeb.AtomControllerTest.__ex_unit_setup_1/1
       test/transport_web/controllers/atom_controller_test.exs:1: TransportWeb.AtomControllerTest.__ex_unit__/2



  6) test aggregates same hour for a given identifier/event (Transport.TelemetryTest)
     test/transport/telemetry_test.exs:13
     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 379ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
     
       1. Ensuring your database is available and that you can connect to it
       2. Tracking down slow queries and making sure they are running fast enough
       3. Increasing the pool_size (although this increases resource consumption)
       4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
     
     See DBConnection.start_link/2 for more information
     
     stacktrace:
       (db_connection 2.4.2) lib/db_connection/ownership.ex:96: DBConnection.Ownership.ownership_checkout/2
       (ecto_sql 3.8.2) lib/ecto/adapters/sql/sandbox.ex:499: Ecto.Adapters.SQL.Sandbox.checkout/2
       test/transport/telemetry_test.exs:6: Transport.TelemetryTest.__ex_unit_setup_0/1
       test/transport/telemetry_test.exs:1: Transport.TelemetryTest.__ex_unit__/2



  7) test requires login (TransportWeb.Backoffice.ProxyConfigLiveTest)
     test/transport_web/live_views/proxy_config_live_test.exs:37
     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 484ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
     
       1. Ensuring your database is available and that you can connect to it
       2. Tracking down slow queries and making sure they are running fast enough
       3. Increasing the pool_size (although this increases resource consumption)
       4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
     
     See DBConnection.start_link/2 for more information
     
     stacktrace:
       (db_connection 2.4.2) lib/db_connection/ownership.ex:96: DBConnection.Ownership.ownership_checkout/2
       (ecto_sql 3.8.2) lib/ecto/adapters/sql/sandbox.ex:499: Ecto.Adapters.SQL.Sandbox.checkout/2
       test/transport_web/live_views/proxy_config_live_test.exs:12: TransportWeb.Backoffice.ProxyConfigLiveTest.__ex_unit_setup_1/1
       test/transport_web/live_views/proxy_config_live_test.exs:1: TransportWeb.Backoffice.ProxyConfigLiveTest.__ex_unit__/2



  8) test OnDemandValidationJob with a gtfs-rt, validator error (Transport.Test.Transport.Jobs.OnDemandValidationJobTest)
     test/transport/jobs/on_demand_validation_job_test.exs:260
     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 506ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
     
       1. Ensuring your database is available and that you can connect to it
       2. Tracking down slow queries and making sure they are running fast enough
       3. Increasing the pool_size (although this increases resource consumption)
       4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
     
     See DBConnection.start_link/2 for more information
     
     stacktrace:
       (db_connection 2.4.2) lib/db_connection/ownership.ex:96: DBConnection.Ownership.ownership_checkout/2
       (ecto_sql 3.8.2) lib/ecto/adapters/sql/sandbox.ex:499: Ecto.Adapters.SQL.Sandbox.checkout/2
       test/transport/jobs/on_demand_validation_job_test.exs:14: Transport.Test.Transport.Jobs.OnDemandValidationJobTest.__ex_unit_setup_1/1
       test/transport/jobs/on_demand_validation_job_test.exs:1: Transport.Test.Transport.Jobs.OnDemandValidationJobTest.__ex_unit__/2



  9) test ResourceUnavailableJob uses latest_url when relevant (Transport.Test.Transport.Jobs.ResourceUnavailableJobTest)
     test/transport/jobs/resource_unavailable_job_test.exs:109
     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 374ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
     
       1. Ensuring your database is available and that you can connect to it
       2. Tracking down slow queries and making sure they are running fast enough
       3. Increasing the pool_size (although this increases resource consumption)
       4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
     
     See DBConnection.start_link/2 for more information
     
     stacktrace:
       (db_connection 2.4.2) lib/db_connection/ownership.ex:96: DBConnection.Ownership.ownership_checkout/2
       (ecto_sql 3.8.2) lib/ecto/adapters/sql/sandbox.ex:499: Ecto.Adapters.SQL.Sandbox.checkout/2
       test/transport/jobs/resource_unavailable_job_test.exs:16: Transport.Test.Transport.Jobs.ResourceUnavailableJobTest.__ex_unit_setup_1/1
       test/transport/jobs/resource_unavailable_job_test.exs:1: Transport.Test.Transport.Jobs.ResourceUnavailableJobTest.__ex_unit__/2



 10) test GTFSRTEntitiesJob removes data over 7 days old (Transport.Test.Transport.Jobs.GTFSRTEntitiesJobTest)
     test/transport/jobs/gtfs_rt_entities_test.exs:70
     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 366ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
     
       1. Ensuring your database is available and that you can connect to it
       2. Tracking down slow queries and making sure they are running fast enough
       3. Increasing the pool_size (although this increases resource consumption)
       4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
     
     See DBConnection.start_link/2 for more information
     
     stacktrace:
       (db_connection 2.4.2) lib/db_connection/ownership.ex:96: DBConnection.Ownership.ownership_checkout/2
       (ecto_sql 3.8.2) lib/ecto/adapters/sql/sandbox.ex:499: Ecto.Adapters.SQL.Sandbox.checkout/2
       test/transport/jobs/gtfs_rt_entities_test.exs:15: Transport.Test.Transport.Jobs.GTFSRTEntitiesJobTest.__ex_unit_setup_1/1
       test/transport/jobs/gtfs_rt_entities_test.exs:1: Transport.Test.Transport.Jobs.GTFSRTEntitiesJobTest.__ex_unit__/2



 11) test DedupeHistoryDispatcherJob it works (Transport.Test.Transport.Jobs.DedupeHistoryJobTest)
     test/transport/jobs/dedupe_history_job_test.exs:20
     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 363ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
     
       1. Ensuring your database is available and that you can connect to it
       2. Tracking down slow queries and making sure they are running fast enough
       3. Increasing the pool_size (although this increases resource consumption)
       4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
     
     See DBConnection.start_link/2 for more information
     
     stacktrace:
       (db_connection 2.4.2) lib/db_connection/ownership.ex:96: DBConnection.Ownership.ownership_checkout/2
       (ecto_sql 3.8.2) lib/ecto/adapters/sql/sandbox.ex:499: Ecto.Adapters.SQL.Sandbox.checkout/2
       test/transport/jobs/dedupe_history_job_test.exs:14: Transport.Test.Transport.Jobs.DedupeHistoryJobTest.__ex_unit_setup_1/1
       test/transport/jobs/dedupe_history_job_test.exs:1: Transport.Test.Transport.Jobs.DedupeHistoryJobTest.__ex_unit__/2

..

 12) doctest Transport.Validators.GTFSTransport.get_max_severity_error/1 (5) (Transport.Validators.GtfsTransportValidatorTest)
     test/transport/validators/gtfs_transport_validator_test.exs:6
     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 193ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
     
       1. Ensuring your database is available and that you can connect to it
       2. Tracking down slow queries and making sure they are running fast enough
       3. Increasing the pool_size (although this increases resource consumption)
       4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
     
     See DBConnection.start_link/2 for more information
     
     stacktrace:
       (db_connection 2.4.2) lib/db_connection/ownership.ex:96: DBConnection.Ownership.ownership_checkout/2
       (ecto_sql 3.8.2) lib/ecto/adapters/sql/sandbox.ex:499: Ecto.Adapters.SQL.Sandbox.checkout/2
       test/transport/validators/gtfs_transport_validator_test.exs:1: Transport.Validators.GtfsTransportValidatorTest.__ex_unit__/2



 13) test disconnected and connected mount refresh stats (TransportWeb.Backoffice.ProxyConfigLiveTest)
     test/transport_web/live_views/proxy_config_live_test.exs:53
     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 193ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
     
       1. Ensuring your database is available and that you can connect to it
       2. Tracking down slow queries and making sure they are running fast enough
       3. Increasing the pool_size (although this increases resource consumption)
       4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
     
     See DBConnection.start_link/2 for more information
     
     stacktrace:
       (db_connection 2.4.2) lib/db_connection/ownership.ex:96: DBConnection.Ownership.ownership_checkout/2
       (ecto_sql 3.8.2) lib/ecto/adapters/sql/sandbox.ex:499: Ecto.Adapters.SQL.Sandbox.checkout/2
       test/transport_web/live_views/proxy_config_live_test.exs:12: TransportWeb.Backoffice.ProxyConfigLiveTest.__ex_unit_setup_1/1
       test/transport_web/live_views/proxy_config_live_test.exs:1: TransportWeb.Backoffice.ProxyConfigLiveTest.__ex_unit__/2



 14) test download url (DB.ResourceTest)
     test/db/resource_test.exs:346
     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 193ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
     
       1. Ensuring your database is available and that you can connect to it
       2. Tracking down slow queries and making sure they are running fast enough
       3. Increasing the pool_size (although this increases resource consumption)
       4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
     
     See DBConnection.start_link/2 for more information
     
     stacktrace:
       (db_connection 2.4.2) lib/db_connection/ownership.ex:96: DBConnection.Ownership.ownership_checkout/2
       (ecto_sql 3.8.2) lib/ecto/adapters/sql/sandbox.ex:499: Ecto.Adapters.SQL.Sandbox.checkout/2
       test/db/resource_test.exs:13: DB.ResourceTest.__ex_unit_setup_1/1
       test/db/resource_test.exs:1: DB.ResourceTest.__ex_unit__/2



 15) test count dataset per format (Transport.StatsHandlerTest)
     test/transport/stats_handler_test.exs:31
     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 193ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
     
       1. Ensuring your database is available and that you can connect to it
       2. Tracking down slow queries and making sure they are running fast enough
       3. Increasing the pool_size (although this increases resource consumption)
       4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
     
     See DBConnection.start_link/2 for more information
     
     stacktrace:
       (db_connection 2.4.2) lib/db_connection/ownership.ex:96: DBConnection.Ownership.ownership_checkout/2
       (ecto_sql 3.8.2) lib/ecto/adapters/sql/sandbox.ex:499: Ecto.Adapters.SQL.Sandbox.checkout/2
       test/transport/stats_handler_test.exs:8: Transport.StatsHandlerTest.__ex_unit_setup_0/1
       test/transport/stats_handler_test.exs:1: Transport.StatsHandlerTest.__ex_unit__/2



 16) test OnDemandValidationJob jsonschema with an exception raised (Transport.Test.Transport.Jobs.OnDemandValidationJobTest)
     test/transport/jobs/on_demand_validation_job_test.exs:143
     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 193ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
     
       1. Ensuring your database is available and that you can connect to it
       2. Tracking down slow queries and making sure they are running fast enough
       3. Increasing the pool_size (although this increases resource consumption)
       4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
     
     See DBConnection.start_link/2 for more information
     
     stacktrace:
       (db_connection 2.4.2) lib/db_connection/ownership.ex:96: DBConnection.Ownership.ownership_checkout/2
       (ecto_sql 3.8.2) lib/ecto/adapters/sql/sandbox.ex:499: Ecto.Adapters.SQL.Sandbox.checkout/2
       test/transport/jobs/on_demand_validation_job_test.exs:14: Transport.Test.Transport.Jobs.OnDemandValidationJobTest.__ex_unit_setup_1/1
       test/transport/jobs/on_demand_validation_job_test.exs:1: Transport.Test.Transport.Jobs.OnDemandValidationJobTest.__ex_unit__/2



 17) test GET /validation/:id with a validation result (TransportWeb.ValidationControllerTest)
     test/transport_web/controllers/validation_controller_test.exs:312
     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 196ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
     
       1. Ensuring your database is available and that you can connect to it
       2. Tracking down slow queries and making sure they are running fast enough
       3. Increasing the pool_size (although this increases resource consumption)
       4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
     
     See DBConnection.start_link/2 for more information
     
     stacktrace:
       (db_connection 2.4.2) lib/db_connection/ownership.ex:96: DBConnection.Ownership.ownership_checkout/2
       (ecto_sql 3.8.2) lib/ecto/adapters/sql/sandbox.ex:499: Ecto.Adapters.SQL.Sandbox.checkout/2
       test/transport_web/controllers/validation_controller_test.exs:17: TransportWeb.ValidationControllerTest.__ex_unit_setup_2/1
       test/transport_web/controllers/validation_controller_test.exs:1: TransportWeb.ValidationControllerTest.__ex_unit__/2



 18) test GTFSRTEntitiesDispatcherJob selects appropriate resources (Transport.Test.Transport.Jobs.GTFSRTEntitiesJobTest)
     test/transport/jobs/gtfs_rt_entities_test.exs:19
     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 193ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
     
       1. Ensuring your database is available and that you can connect to it
       2. Tracking down slow queries and making sure they are running fast enough
       3. Increasing the pool_size (although this increases resource consumption)
       4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
     
     See DBConnection.start_link/2 for more information
     
     stacktrace:
       (db_connection 2.4.2) lib/db_connection/ownership.ex:96: DBConnection.Ownership.ownership_checkout/2
       (ecto_sql 3.8.2) lib/ecto/adapters/sql/sandbox.ex:499: Ecto.Adapters.SQL.Sandbox.checkout/2
       test/transport/jobs/gtfs_rt_entities_test.exs:15: Transport.Test.Transport.Jobs.GTFSRTEntitiesJobTest.__ex_unit_setup_1/1
       test/transport/jobs/gtfs_rt_entities_test.exs:1: Transport.Test.Transport.Jobs.GTFSRTEntitiesJobTest.__ex_unit__/2



 19) test is_same? different objects (Transport.Test.Transport.Jobs.DedupeHistoryJobTest)
     test/transport/jobs/dedupe_history_job_test.exs:39
     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 193ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
     
       1. Ensuring your database is available and that you can connect to it
       2. Tracking down slow queries and making sure they are running fast enough
       3. Increasing the pool_size (although this increases resource consumption)
       4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
     
     See DBConnection.start_link/2 for more information
     
     stacktrace:
       (db_connection 2.4.2) lib/db_connection/ownership.ex:96: DBConnection.Ownership.ownership_checkout/2
       (ecto_sql 3.8.2) lib/ecto/adapters/sql/sandbox.ex:499: Ecto.Adapters.SQL.Sandbox.checkout/2
       test/transport/jobs/dedupe_history_job_test.exs:14: Transport.Test.Transport.Jobs.DedupeHistoryJobTest.__ex_unit_setup_1/1
       test/transport/jobs/dedupe_history_job_test.exs:1: Transport.Test.Transport.Jobs.DedupeHistoryJobTest.__ex_unit__/2



 20) test ResourceUnavailableJob when there is an ongoing unavailability and the resource stays unavailable (Transport.Test.Transport.Jobs.ResourceUnavailableJobTest)
     test/transport/jobs/resource_unavailable_job_test.exs:63
     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 193ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
     
       1. Ensuring your database is available and that you can connect to it
       2. Tracking down slow queries and making sure they are running fast enough
       3. Increasing the pool_size (although this increases resource consumption)
       4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
     
     See DBConnection.start_link/2 for more information
     
     stacktrace:
       (db_connection 2.4.2) lib/db_connection/ownership.ex:96: DBConnection.Ownership.ownership_checkout/2
       (ecto_sql 3.8.2) lib/ecto/adapters/sql/sandbox.ex:499: Ecto.Adapters.SQL.Sandbox.checkout/2
       test/transport/jobs/resource_unavailable_job_test.exs:16: Transport.Test.Transport.Jobs.ResourceUnavailableJobTest.__ex_unit_setup_1/1
       test/transport/jobs/resource_unavailable_job_test.exs:1: Transport.Test.Transport.Jobs.ResourceUnavailableJobTest.__ex_unit__/2

............................................................................................................................................................................................................................................................................................................................................

Finished in 15.9 seconds (3.6s async, 12.3s sync)
92 doctests, 429 tests, 20 failures, 4 excluded
```

</details>

Ca devient relativement fréquent donc je crée un ticket pour tracer et partager, il faudra voir à quoi c'est lié.

**Comment by AntoineAugusti** [comment]
Ça m'arrive de temps en temps, ou en lançant un `phx.server`.

**Comment by thbar** [comment]
Même un passage de `pool_size` à `100` ne suffit pas tout le temps.

Commande utilisée: `mix cmd mix test --warnings-as-errors --color`

**Comment by AntoineAugusti** [comment]
Pas vu depuis longtemps

**Comment by thbar** [comment]
Ca semble bien traité par mon fix dans #2673 via:

https://github.com/etalab/transport-site/blob/609ce374afbc276253a2b67c743254a4ff06bf29/config/test.exs#L86-L89

@AntoineAugusti si tu as cela de nouveau en dév, on saura qu'on peut ajuster dans la config de dév également au pire.

Je clôture, une de moins !
