### ISSUE TITLE
"400 - requête incorrecte" sur validation à la demande

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2678]
Je pense avoir introduit une petite régression ici :

https://github.com/etalab/transport-site/pull/2673/files#diff-bbc2bba43bab332f51b102d6a3828d216cf9f6d7323519f36bbbdf1ed42164ca

J'ai été tester la validation à la demande (https://transport.data.gouv.fr/validation?type=gtfs) et j'obtiens une erreur.

Je vais enquêter et préparer un fix.

**Comment by thbar** [comment]
Quelques tests:
- en local, sur master, une validation GTFS fonctionne (tignes)
- en production, la même échoue
- en production, une validation GBFS réussit

**Comment by thbar** [comment]
Logs correspondants quand je déclenche l'erreur:

```
2022-09-27T15:18:01+02:00 15:18:01.793 request_id=Fxi6Ga9yrQkSfGwAA2Bi [info] GET /gbfs/toulouse/free_bike_status.json
2022-09-27T15:18:01+02:00 15:18:01.794 [error] #PID<0.19999.2> running TransportWeb.Endpoint (connection #PID<0.19998.2>, stream id 1) terminated
2022-09-27T15:18:01+02:00 Server: transport.data.gouv.fr:80 (http)
2022-09-27T15:18:01+02:00 Request: GET /gbfs/toulouse/free_bike_status.json
2022-09-27T15:18:01+02:00 ** (exit) an exception was raised:
2022-09-27T15:18:01+02:00 ** (ArgumentError) session not fetched, call fetch_session/2
2022-09-27T15:18:01+02:00 (plug 1.13.6) lib/plug/conn.ex:1567: Plug.Conn.get_session/1
2022-09-27T15:18:01+02:00 (plug 1.13.6) lib/plug/conn.ex:1550: Plug.Conn.get_session/2
2022-09-27T15:18:01+02:00 (transport 0.0.1) lib/transport_web/templates/layout/app.html.heex:2: anonymous fn/2 in TransportWeb.LayoutView."app.html"/1
2022-09-27T15:18:01+02:00 (phoenix_live_view 0.18.0) lib/phoenix_live_view/engine.ex:128: Phoenix.HTML.Safe.Phoenix.LiveView.Rendered.to_iodata/1
2022-09-27T15:18:01+02:00 (phoenix 1.6.12) lib/phoenix/controller.ex:772: Phoenix.Controller.render_and_send/4
2022-09-27T15:18:01+02:00 (phoenix 1.6.12) lib/phoenix/endpoint/render_errors.ex:78: Phoenix.Endpoint.RenderErrors.instrument_render_and_send/5
2022-09-27T15:18:01+02:00 (phoenix 1.6.12) lib/phoenix/endpoint/render_errors.ex:64: Phoenix.Endpoint.RenderErrors.__catch__/5
2022-09-27T15:18:01+02:00 (phoenix 1.6.12) lib/phoenix/endpoint/cowboy2_handler.ex:54: Phoenix.Endpoint.Cowboy2Handler.init/4
2022-09-27T15:18:01+02:00 15:18:01.840 request_id=Fxi6GbI7jbON5hIAA2CC [info] GET /resource/ilevia-lille-gtfs-rt
2022-09-27T15:18:01+02:00 15:18:01.841 [info] Telemetry event: processing external proxy request for proxy:ilevia-lille-gtfs-rt
2022-09-27T15:18:01+02:00 15:18:01.841 [info] Processing proxy request for identifier ilevia-lille-gtfs-rt
2022-09-27T15:18:01+02:00 15:18:01.841 [info] Telemetry event: processing internal proxy request for proxy:ilevia-lille-gtfs-rt
2022-09-27T15:18:02+02:00 15:18:01.915 request_id=Fxi6GbawWWteTJoAA2DC [info] GET /gbfs/vcub/system_information.json
2022-09-27T15:18:02+02:00 15:18:01.915 request_id=Fxi6GbawWWteTJoAA2DC [info] Cache hit for key page:/gbfs/vcub/system_information.json
2022-09-27T15:18:02+02:00 15:18:01.915 request_id=Fxi6GbawWWteTJoAA2DC [info] Sent 200 in 236µs
2022-09-27T15:18:02+02:00 15:18:01.915 [info] Telemetry event: processing external GBFS request for gbfs:vcub
```

**Comment by thbar** [comment]
Je vais aller voir pour rejouer ça sur "prochainement", il y aura moins de bruit.

**Comment by thbar** [comment]
Ca reproduit bien le souci, mais rien dans les logs.
