### ISSUE TITLE
Test fragile DataChecker

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2947]
```
  1) test inactive_data job warns our team of datasets disappearing on data gouv and mark them as such locally (Transport.DataCheckerTest)
     apps/transport/test/transport/data_checker_test.exs:47
     ** (FunctionClauseError) no function clause matching in anonymous fn/5 in Transport.DataCheckerTest."test inactive_data job warns our team of datasets disappearing on data gouv and mark them as such locally"/1

     The following arguments were given to anonymous fn/5 in Transport.DataCheckerTest."test inactive_data job warns our team of datasets disappearing on data gouv and mark them as such locally"/1:
     
         # 1
         :get
     
         # 2
         "https://demo.data.gouv.fr/api/1/datasets/bee58c3f-6179-4fca-a9e0-613503dcb874/"
     
         # 3
         ""
     
         # 4
         []
     
         # 5
         [follow_redirect: true]
     
     code: Transport.DataChecker.inactive_data()
     stacktrace:
       test/transport/data_checker_test.exs:55: anonymous fn/5 in Transport.DataCheckerTest."test inactive_data job warns our team of datasets disappearing on data gouv and mark them as such locally"/1
       (datagouvfr 0.1.0) lib/datagouvfr/client/api.ex:111: Datagouvfr.Client.API.perform_request/6
       (datagouvfr 0.1.0) lib/datagouvfr/client/api.ex:95: Datagouvfr.Client.API.request_url/5
       (transport 0.0.1) lib/transport/data_checker.ex:67: Transport.DataChecker.dataset_status/1
       (transport 0.0.1) lib/transport/data_checker.ex:62: anonymous fn/1 in Transport.DataChecker.datasets_datagouv_statuses/0
       (elixir 1.14.1) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
       (transport 0.0.1) lib/transport/data_checker.ex:24: Transport.DataChecker.inactive_data/0
       test/transport/data_checker_test.exs:81: (test)
```

**Comment by thbar** [comment]
C'est une question d'ordre. En ajoutant des puts, et en lançant uniquement ce test en local de multiples fois, je vois que j'ai bien une erreur de match lié à l'ordre:

```
https://demo.data.gouv.fr/api/1/datasets/62f17ba9-e518-4218-991a-72677324d858/
https://demo.data.gouv.fr/api/1/datasets/29c20a10-98df-4290-be18-27508a7ff62c/
https://demo.data.gouv.fr/api/1/datasets/518ca1e4-b359-4e82-994c-0741412ed1e3/
https://demo.data.gouv.fr/api/1/datasets/dcff7bbc-049c-4c49-b881-aba5b350828a/
https://demo.data.gouv.fr/api/1/datasets/e360fb38-7224-4a74-9885-4d0540e9710e/
https://demo.data.gouv.fr/api/1/datasets/992ebc7c-49d1-4517-8821-c394f3890797/
https://demo.data.gouv.fr/api/1/datasets/47c5fd79-4e09-4f89-a34e-79898ad4ffa4/
https://demo.data.gouv.fr/api/1/datasets/e40346ac-846f-4c77-9931-87224c4da771/
https://demo.data.gouv.fr/api/1/datasets/95540b1e-1a81-49d8-9e31-abf455477bfb/
https://demo.data.gouv.fr/api/1/datasets/272c770c-c825-45cd-a1a2-b3e7e4bced71/
```

Puis l'erreur porte sur le deuxième item:

```
The following arguments were given to anonymous fn/5 in Transport.DataCheckerTest."test inactive_data job warns our team of datasets disappearing on data gouv and mark them as such locally"/1:
     
         # 1
         :get
     
         # 2
         "https://demo.data.gouv.fr/api/1/datasets/29c20a10-98df-4290-be18-27508a7ff62c/"
```
