### ISSUE TITLE
Données TR affichées sur le PAN pour Transvilles alors qu'absentes de data.gouv

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#3002]
Hello, 
Les données TR de Transvilles ont bien été supprimées depuis l'espace admin du jeu de données dans data.gouv mais pourtant elles figurent toujours sur le PAN : 
<img width="628" alt="image" src="https://user-images.githubusercontent.com/101095139/222508495-5d64f77d-f021-41f2-881f-00ae3266dacd.png">

J'ai peut-être loupé un truc mais je ne comprends pas bien pourquoi ? 
Merci

**Comment by AntoineAugusti** [comment]
L'import de ce JDD n'a pas été effectué correctement depuis plusieurs jours d'où l'absence de synchro.

Voici ce qu'il y a sur le backoffice.

![image](https://user-images.githubusercontent.com/295709/222670041-c6d86fa7-963a-4af6-a138-b7392bde18c8.png)

Je regarde

**Comment by AntoineAugusti** [comment]
Ça vient d'une requête de suppression trop longue, on a mis plus de 15s à supprimer la 78979 (un GTFS-RT).

```
UPDATE "dataset" SET "full_logo" = $1, "has_realtime" = $2, "last_update" = $3, "logo" = $4, "updated_at" = $5 WHERE "id" = $6 ["https://static.data.gouv.fr/avatars/d8/c9de6a276246a6a69b99a774fb497e-original.jpg", false, "2022-02-24", "https://static.data.gouv.fr/avatars/d8/c9de6a276246a6a69b99a774fb497e-100.jpg", ~U[2023-03-03 08:27:56.305629Z], 386]
[debug] QUERY OK source="resource_unavailability" db=9.3ms
DELETE FROM "resource_unavailability" AS r0 WHERE (r0."resource_id" = $1) [78979]
[error] Postgrex.Protocol (#PID<0.2994.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.3289.0> timed out because it queued and checked out the connection for longer than 15000ms

#PID<0.3289.0> was at location:

    :prim_inet.recv0/3
    (postgrex 0.16.5) lib/postgrex/protocol.ex:3171: Postgrex.Protocol.msg_recv/4
    (postgrex 0.16.5) lib/postgrex/protocol.ex:2201: Postgrex.Protocol.recv_bind/3
    (postgrex 0.16.5) lib/postgrex/protocol.ex:2093: Postgrex.Protocol.bind_execute/4
    (db_connection 2.4.3) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.4.3) lib/db_connection.ex:1413: DBConnection.run_execute/5
    (db_connection 2.4.3) lib/db_connection.ex:644: DBConnection.parsed_prepare_execute/5
    (db_connection 2.4.3) lib/db_connection.ex:636: DBConnection.prepare_execute/4
    (postgrex 0.16.5) lib/postgrex.ex:340: Postgrex.query/4
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:955: Ecto.Adapters.SQL.struct/10
    (ecto 3.9.4) lib/ecto/repo/schema.ex:756: Ecto.Repo.Schema.apply/4
    (ecto 3.9.4) lib/ecto/repo/schema.ex:552: anonymous fn/11 in Ecto.Repo.Schema.do_delete/4
    (ecto 3.9.4) lib/ecto/association.ex:815: Ecto.Association.Has.on_repo_change/5
    (ecto 3.9.4) lib/ecto/association.ex:801: Ecto.Association.Has.on_repo_change/5
    (ecto 3.9.4) lib/ecto/association.ex:573: anonymous fn/8 in Ecto.Association.on_repo_change/7
    (elixir 1.14.1) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.9.4) lib/ecto/association.ex:569: Ecto.Association.on_repo_change/7
    (elixir 1.14.1) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.9.4) lib/ecto/association.ex:533: Ecto.Association.on_repo_change/4
    (ecto 3.9.4) lib/ecto/repo/schema.ex:917: Ecto.Repo.Schema.process_children/5

[debug] QUERY ERROR db=12235.4ms
DELETE FROM "resource" WHERE "id" = $1 [78979]
[debug] QUERY ERROR db=0.0ms
rollback []
[debug] QUERY OK db=8.4ms queue=22.7ms idle=1959.5ms
INSERT INTO "logs_import" ("datagouv_id","dataset_id","error_msg","is_success","timestamp") VALUES ($1,$2,$3,$4,$5) RETURNING "id" ["5e5640aa634f412ab4f8353e", 386, "%DBConnection.ConnectionError{message: \"tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)\", severity: :error, reason: :error}", false, ~U[2023-03-03 08:28:11Z]]
[error] Import of dataset has failed (id:  386, datagouv_id: 5e5640aa634f412ab4f8353e)
[error] ** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto 3.9.4) lib/ecto/repo/schema.ex:756: Ecto.Repo.Schema.apply/4
    (ecto 3.9.4) lib/ecto/repo/schema.ex:552: anonymous fn/11 in Ecto.Repo.Schema.do_delete/4
    (ecto 3.9.4) lib/ecto/association.ex:815: Ecto.Association.Has.on_repo_change/5
    (ecto 3.9.4) lib/ecto/association.ex:801: Ecto.Association.Has.on_repo_change/5
    (ecto 3.9.4) lib/ecto/association.ex:573: anonymous fn/8 in Ecto.Association.on_repo_change/7
    (elixir 1.14.1) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.9.4) lib/ecto/association.ex:569: Ecto.Association.on_repo_change/7
    (elixir 1.14.1) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.9.4) lib/ecto/association.ex:533: Ecto.Association.on_repo_change/4
    (ecto 3.9.4) lib/ecto/repo/schema.ex:917: Ecto.Repo.Schema.process_children/5
    (ecto 3.9.4) lib/ecto/repo/schema.ex:995: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1203: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.4.3) lib/db_connection.ex:1611: DBConnection.run_transaction/4
    (ecto 3.9.4) lib/ecto/repo/schema.ex:278: Ecto.Repo.Schema.update!/4
    (transport 0.0.1) lib/transport/import_data.ex:109: Transport.ImportData.import_dataset!/1
    (transport 0.0.1) lib/transport/import_data.ex:89: Transport.ImportData.import_dataset_logged/1
    (transport 0.0.1) lib/transport_web/controllers/backoffice/dataset_controller.ex:96: TransportWeb.Backoffice.DatasetController.import_from_data_gouv_fr_aux/2
    (transport 0.0.1) lib/transport_web/controllers/backoffice/dataset_controller.ex:87: TransportWeb.Backoffice.DatasetController.import_from_data_gouv_fr/2
    (transport 0.0.1) lib/transport_web/controllers/backoffice/dataset_controller.ex:1: TransportWeb.Backoffice.DatasetController.action/2
```

## Clés étrangères de `resource.id`

schema_name|constraint_name|table_name|col_name|foreign_table_schema|foreign_table_name|foreign_col_name
-- | -- | -- | -- | -- | -- | --
public | dataset_history_resources_resource_id_fkey | dataset_history_resources | resource_id | public | resource | id
public | multi_validation_resource_id_fkey | multi_validation | resource_id | public | resource | id
public | multi_validation_secondary_resource_id_fkey | multi_validation | secondary_resource_id | public | resource | id
public | resource_history_resource_id_fkey | resource_history | resource_id | public | resource | id
public | resource_metadata_resource_id_fkey | resource_metadata | resource_id | public | resource | id
public | resource_unavailability_resource_id_fkey | resource_unavailability | resource_id | public | resource | id

Me semble pas manquer d'indexs sur ces colonnes, je regarde donc le query plan.

## SQL query plan pour la suppression

```sql
EXPLAIN ANALYZE VERBOSE DELETE FROM "resource" WHERE "id" = 78979;

Delete on public.resource  (cost=0.28..2.50 rows=0 width=0) (actual time=0.163..0.164 rows=0 loops=1)
  ->  Index Scan using resource_pkey on public.resource  (cost=0.28..2.50 rows=1 width=6) (actual time=0.037..0.039 rows=1 loops=1)
        Output: ctid
        Index Cond: (resource.id = 78979)
Query Identifier: -8669690689419375784
Planning Time: 0.128 ms
Trigger RI_ConstraintTrigger_a_255122 for constraint multi_validation_resource_id_fkey on resource: time=7.086 calls=1
Trigger RI_ConstraintTrigger_a_255132 for constraint multi_validation_secondary_resource_id_fkey on resource: time=38.970 calls=1
Trigger RI_ConstraintTrigger_a_255151 for constraint resource_metadata_resource_id_fkey on resource: time=22.325 calls=1
Trigger RI_ConstraintTrigger_a_32612 for constraint resource_unavailability_resource_id_fkey on resource: time=0.303 calls=1
Trigger RI_ConstraintTrigger_a_3315758 for constraint dataset_history_resources_resource_id_fkey on resource: time=75.661 calls=1
Trigger RI_ConstraintTrigger_a_360378 for constraint resource_history_resource_id_fkey on resource: time=0.326 calls=1
Trigger RI_ConstraintTrigger_a_255161 for constraint resource_metadata_multi_validation_id_fkey on multi_validation: time=16.677 calls=187
Trigger RI_ConstraintTrigger_a_3315773 for constraint dataset_history_resources_validation_id_fkey on multi_validation: time=4478.490 calls=187
Trigger RI_ConstraintTrigger_a_3315768 for constraint dataset_history_resources_resource_metadata_id_fkey on resource_metadata: time=41684.163 calls=1753
Trigger RI_ConstraintTrigger_c_3252701 for constraint dataset_history_resources_dataset_history_id_fkey on dataset_history_resources: time=22.952 calls=176
Trigger RI_ConstraintTrigger_c_3315771 for constraint dataset_history_resources_resource_metadata_id_fkey on dataset_history_resources: time=0.043 calls=88
Execution Time: 46349.953 ms
```

Semble manquer 2 index dans `dataset_history_resources` pour `dataset_history_id` et `resource_metadata_id`. Je les ajoute pour voir l'impact.

```sql
EXPLAIN ANALYZE VERBOSE DELETE FROM "resource" WHERE "id" = 78979;
Delete on public.resource  (cost=0.28..2.50 rows=0 width=0) (actual time=0.025..0.026 rows=0 loops=1)
  ->  Index Scan using resource_pkey on public.resource  (cost=0.28..2.50 rows=1 width=6) (actual time=0.024..0.024 rows=0 loops=1)
        Output: ctid
        Index Cond: (resource.id = 78979)
Query Identifier: -8669690689419375784
Planning Time: 0.100 ms
Execution Time: 0.062 ms
```

donc prévoir d'ajouter ces 2 index ! cc @fchabouis 

En attendant je supprime la ressource à la main pour débloquer la situation.

**Comment by AntoineAugusti** [comment]
@ChristinaLaumond L'import [de ce JDD](https://transport.data.gouv.fr/datasets/simouv-horaires-theoriques-et-temps-reel-de-transport-public-transvilles-valenciennes) est bon désormais !

Merci d'avoir reporté le bug 👍
