### ISSUE TITLE
Deadlock en exécutant des tests : ERROR 40P01 (deadlock_detected)

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3360]
```
Randomized with seed 559459
==> transport
Excluding tags: [:pending]

...............................................................................................................................................................................................

  1) test marks for deletion relevant rows when deleting by dataset_id (Transport.Test.Transport.Jobs.RemoveHistoryJobTest)
     apps/transport/test/transport/jobs/remove_history_job_test.exs:41
     ** (Postgrex.Error) ERROR 40P01 (deadlock_detected) deadlock detected
     
         hint: See server log for query details.
     
     Process 1559 waits for AccessExclusiveLock on relation 20346 of database 16384; blocked by process 1562.
     Process 1562 waits for ShareLock on transaction 1503; blocked by process 1554.
     Process 1554 waits for AccessExclusiveLock on relation 20346 of database 16384; blocked by process 1559.
     code: %{id: dataset_id} = dataset = insert(:dataset, type: "bike-scooter-sharing")
     stacktrace:
       (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
       (ecto 3.10.1) lib/ecto/repo/schema.ex:764: Ecto.Repo.Schema.apply/4
       (ecto 3.10.1) lib/ecto/repo/schema.ex:377: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
       (ecto 3.10.1) lib/ecto/association.ex:1084: Ecto.Association.BelongsTo.on_repo_change/5
       (ecto 3.10.1) lib/ecto/association.ex:555: Ecto.Association.on_repo_change/7
       (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto 3.10.1) lib/ecto/association.ex:533: Ecto.Association.on_repo_change/4
       (ecto 3.10.1) lib/ecto/repo/schema.ex:894: Ecto.Repo.Schema.process_parents/5
       (ecto 3.10.1) lib/ecto/repo/schema.ex:351: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
       (ecto 3.10.1) lib/ecto/association.ex:1084: Ecto.Association.BelongsTo.on_repo_change/5
       (ecto 3.10.1) lib/ecto/association.ex:555: Ecto.Association.on_repo_change/7
       (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto 3.10.1) lib/ecto/association.ex:533: Ecto.Association.on_repo_change/4
       (ecto 3.10.1) lib/ecto/repo/schema.ex:894: Ecto.Repo.Schema.process_parents/5
       (ecto 3.10.1) lib/ecto/repo/schema.ex:351: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
       (ecto 3.10.1) lib/ecto/repo/schema.ex:1004: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1203: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
       (db_connection 2.5.0) lib/db_connection.ex:1630: DBConnection.run_transaction/4
       (ecto 3.10.1) lib/ecto/repo/schema.ex:273: Ecto.Repo.Schema.insert!/4
       test/transport/jobs/remove_history_job_test.exs:42: (test)



  2) test updates relevant notification subscriptions (Transport.Test.Transport.Jobs.NotificationSubscriptionProducerJobTest)
     apps/transport/test/transport/jobs/notification_subscription_producer_job_test.exs:11
     ** (Postgrex.Error) ERROR 40P01 (deadlock_detected) deadlock detected
     
         hint: See server log for query details.
     
     Process 1554 waits for AccessExclusiveLock on relation 20346 of database 16384; blocked by process 1562.
     Process 1562 waits for ShareLock on transaction 1503; blocked by process 1554.
     code: dataset = insert(:dataset, organization_id: org_id)
     stacktrace:
       (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
       (ecto 3.10.1) lib/ecto/repo/schema.ex:764: Ecto.Repo.Schema.apply/4
       (ecto 3.10.1) lib/ecto/repo/schema.ex:377: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
       (ecto 3.10.1) lib/ecto/association.ex:1084: Ecto.Association.BelongsTo.on_repo_change/5
       (ecto 3.10.1) lib/ecto/association.ex:555: Ecto.Association.on_repo_change/7
       (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto 3.10.1) lib/ecto/association.ex:533: Ecto.Association.on_repo_change/4
       (ecto 3.10.1) lib/ecto/repo/schema.ex:894: Ecto.Repo.Schema.process_parents/5
       (ecto 3.10.1) lib/ecto/repo/schema.ex:351: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
       (ecto 3.10.1) lib/ecto/association.ex:1084: Ecto.Association.BelongsTo.on_repo_change/5
       (ecto 3.10.1) lib/ecto/association.ex:555: Ecto.Association.on_repo_change/7
       (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto 3.10.1) lib/ecto/association.ex:533: Ecto.Association.on_repo_change/4
       (ecto 3.10.1) lib/ecto/repo/schema.ex:894: Ecto.Repo.Schema.process_parents/5
       (ecto 3.10.1) lib/ecto/repo/schema.ex:351: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
       (ecto 3.10.1) lib/ecto/repo/schema.ex:1004: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1203: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
       (db_connection 2.5.0) lib/db_connection.ex:1630: DBConnection.run_transaction/4
       (ecto 3.10.1) lib/ecto/repo/schema.ex:273: Ecto.Repo.Schema.insert!/4
       test/transport/jobs/notification_subscription_producer_job_test.exs:29: (test)

......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................thread 'main' panicked at 'The GTFS file is not well formated.: NotFileNorDirectory("")', src/main.rs:42:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
...............................................................................................................................................
Finished in 47.6 seconds (23.6s async, 23.9s sync)
151 doctests, 751 tests, 2 failures

Randomized with seed 559459
```

**Comment by AntoineAugusti** [comment]
Pas revu depuis
