### ISSUE TITLE
Test qui échoue (mais que le lundi 😄)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3868]
Découvert en bossant sur:
- #3815 

```
  1) test perform sends an email (Transport.Test.Transport.Jobs.NewDatagouvDatasetsJobTest)
     apps/transport/test/transport/jobs/new_datagouv_datasets_job_test.exs:163
     Assertion with =~ failed
     code:  assert body =~ ~s"Les jeux de données suivants ont été ajoutés sur data.gouv.fr dans les dernières 24h"
     left:  "Bonjour,\n\nLes jeux de données suivants ont été ajoutés sur data.gouv.fr dans les dernières 72h et sont susceptibles d'avoir leur place sur le PAN :\n\n* GTFS de Dijon - https://example.com/link\n\n---\nVous pouvez consulter et modifier les règles de cette tâche : https://github.com/etalab/transport-site/blob/master/apps/transport/lib/jobs/new_datagouv_datasets_job.ex\n"
     right: "Les jeux de données suivants ont été ajoutés sur data.gouv.fr dans les dernières 24h"
     stacktrace:
       (transport 0.0.1) lib/jobs/new_datagouv_datasets_job.ex:51: Transport.Jobs.NewDatagouvDatasetsJob.perform/1
       (oban 2.17.6) lib/oban/queue/executor.ex:129: Oban.Queue.Executor.perform/1
       (oban 2.17.6) lib/oban/queue/executor.ex:74: Oban.Queue.Executor.call/1
       (oban 2.17.6) lib/oban/testing.ex:228: Oban.Testing.perform_job/3
       test/transport/jobs/new_datagouv_datasets_job_test.exs:198: (test)
```

On peut:
- rendre le test plus tranquille en testant moins (en enlevant la notion d'heures sur le texte)
- mocker le temps (on y viendra)
- ou faire du conditional

**Comment by thbar** [comment]
Je fais un petit correctif ça vous va @etalab/transport-tech ?

**Comment by thbar** [comment]
(sauf si quelqu'un a déjà réglé ça sur une branche)

**Comment by thbar** [comment]
Je prépare un premier correctif basique pour débloquer les builds.

**Comment by ptitfred** [comment]
Je ne comprends pas comment ce test peut être sensible à la date courante, il teste des dates du passé lointain.

**Comment by ptitfred** [comment]
> Je ne comprends pas comment ce test peut être sensible à la date courante, il teste des dates du passé lointain.

ok j'ai parlé trop vite, c'est l'autre test qui a été rendu insensible à la date courante.

**Comment by thbar** [comment]
> ok j'ai parlé trop vite, c'est l'autre test qui a été rendu insensible à la date courante.

Yes tout à fait !

**Comment by thbar** [comment]
Vu avec @ptitfred en DM, il va gérer ! (merci !)

**Comment by thbar** [comment]
C'est traité, merci @ptitfred !
