### ISSUE TITLE
Logs d'erreurs curieux (en dév)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#4279]
@etalab/transport-tech avez-vous déjà vu ce log ? Je l'ai rencontré quelques fois, je n'ai pas encore creusé mais je note vu que ce n'est pas la première fois.

Le premier log concerne le détachement du handler permettant à AppSignal de remonter les logs (mais rien n'indique à ce stade que c'est la cause de l'ensemble des autres erreurs)

https://github.com/etalab/transport-site/blob/b06203f7b97e667fa165c25bd5dd45d00a47c1e6/apps/transport/lib/transport/ecto_telemetry.ex#L70-L71

### Logs

```
webpack 5.88.2 compiled successfully in 4493 ms
[error] Handler "transport-ecto" has failed and has been detached. Class=:error
Reason=:undef
Stacktrace=[
  {Transport.EctoTelemetry, :handle_event,
   [
     [:db, :repo, :query],
     %{
       idle_time: 1642072039,
       query_time: 125880,
       queue_time: 20531,
       total_time: 146411
     },
     %{
       cast_params: nil,
       options: [
         oban_conf: %Oban.Config{
           dispatch_cooldown: 5,
           engine: Oban.Engines.Basic,
           get_dynamic_repo: nil,
           insert_trigger: false,
           log: false,
           name: Oban,
           node: "DESKTOP-H18V67H",
           notifier: {Oban.Notifiers.Postgres, []},
           peer: {Oban.Peers.Postgres, []},
           plugins: [
             {Oban.Plugins.Cron, [crontab: []]},
             {Oban.Plugins.Lifeline, [rescue_after: 3600000]},
             {Oban.Plugins.Pruner, [max_age: 86400]}
           ],
           prefix: "public",
           queues: [
             default: [limit: 2],
             enroute_conversions: [limit: 10],
             heavy: [limit: 1],
             on_demand_validation: [limit: 1],
             resource_validation: [limit: 1],
             workflow: [limit: 2]
           ],
           repo: DB.Repo,
           shutdown_grace_period: 15000,
           stage_interval: 1000,
           testing: :disabled
         }
       ],
       params: [],
       query: "begin",
       repo: DB.Repo,
       result: {:ok,
        %Postgrex.Result{
          command: :begin,
          columns: nil,
          rows: nil,
          num_rows: nil,
          connection_id: 1952,
          messages: []
        }},
       source: nil,
       stacktrace: nil,
       type: :ecto_sql_query
     },
     nil
   ], []},
  {:telemetry, :"-execute/3-fun-0-", 4,
   [
     file: ~c"/Users/thbar/git/transport/transport-site/deps/telemetry/src/telemetry.erl",
     line: 160
   ]},
  {:lists, :foreach_1, 2, [file: ~c"lists.erl", line: 1442]},
  {Ecto.Adapters.SQL, :log, 4, [file: ~c"lib/ecto/adapters/sql.ex", line: 1234]},
  {DBConnection, :log, 5, [file: ~c"lib/db_connection.ex", line: 1704]},
  {DBConnection, :transaction, 3, [file: ~c"lib/db_connection.ex", line: 1080]},
  {Oban.Stager, :stage_and_notify, 2, [file: ~c"lib/oban/stager.ex", line: 70]},
  {Oban.Stager, :"-handle_info/2-fun-0-", 2,
   [file: ~c"lib/oban/stager.ex", line: 57]},
  {:telemetry, :span, 3,
   [
     file: ~c"/Users/thbar/git/transport/transport-site/deps/telemetry/src/telemetry.erl",
     line: 321
   ]},
  {Oban.Stager, :handle_info, 2, [file: ~c"lib/oban/stager.ex", line: 56]},
  {:gen_server, :try_dispatch, 4, [file: ~c"gen_server.erl", line: 1123]},
  {:gen_server, :handle_msg, 6, [file: ~c"gen_server.erl", line: 1200]},
  {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 240]}
]

==> transport
Compiling 303 files (.ex)
[error] GenServer {Oban.Registry, {Oban, Oban.Stager}} terminating
** (UndefinedFunctionError) function DB.PostgrexTypes.encode_params/2 is undefined (module DB.PostgrexTypes is not available)
    (transport 0.0.1) DB.PostgrexTypes.encode_params(["available", ~U[2024-10-29 07:45:41.887711Z], 5000], [Postgrex.Extensions.Raw, Postgrex.Extensions.Timestamp, Postgrex.Extensions.Int8])
    (postgrex 0.16.5) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3
    (db_connection 2.7.0) lib/db_connection.ex:1462: DBConnection.maybe_encode/4
    (db_connection 2.7.0) lib/db_connection.ex:823: DBConnection.execute/4
    (ecto_sql 3.11.3) lib/ecto/adapters/postgres/connection.ex:133: Ecto.Adapters.Postgres.Connection.execute/4
    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:996: Ecto.Adapters.SQL.execute!/5
    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
    (ecto 3.11.2) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
    (oban 2.18.0) lib/oban/engines/basic.ex:142: Oban.Engines.Basic.stage_jobs/3
    (oban 2.18.0) lib/oban/engine.ex:244: anonymous fn/4 in Oban.Engine.stage_jobs/3
    (oban 2.18.0) lib/oban/engine.ex:339: anonymous fn/3 in Oban.Engine.with_span/4
    (telemetry 1.2.1) /Users/thbar/git/transport/transport-site/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (oban 2.18.0) lib/oban/stager.ex:71: anonymous fn/1 in Oban.Stager.stage_and_notify/2
    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:1358: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.7.0) lib/db_connection.ex:1756: DBConnection.run_transaction/4
    (oban 2.18.0) lib/oban/stager.ex:70: Oban.Stager.stage_and_notify/2
    (oban 2.18.0) lib/oban/stager.ex:57: anonymous fn/2 in Oban.Stager.handle_info/2
    (telemetry 1.2.1) /Users/thbar/git/transport/transport-site/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (oban 2.18.0) lib/oban/stager.ex:56: Oban.Stager.handle_info/2
    (stdlib 4.3.1.3) gen_server.erl:1123: :gen_server.try_dispatch/4
Last message: :stage
State: %Oban.Stager{conf: %Oban.Config{dispatch_cooldown: 5, engine: Oban.Engines.Basic, get_dynamic_repo: nil, insert_trigger: false, log: false, name: Oban, node: "DESKTOP-H18V67H", notifier: {Oban.Notifiers.Postgres, []}, peer: {Oban.Peers.Postgres, []}, plugins: [{Oban.Plugins.Cron, [crontab: []]}, {Oban.Plugins.Lifeline, [rescue_after: 3600000]}, {Oban.Plugins.Pruner, [max_age: 86400]}], prefix: "public", queues: [default: [limit: 2], enroute_conversions: [limit: 10], heavy: [limit: 1], on_demand_validation: [limit: 1], resource_validation: [limit: 1], workflow: [limit: 2]], repo: DB.Repo, shutdown_grace_period: 15000, stage_interval: 1000, testing: :disabled}, timer: #Reference<0.2890691434.1772879873.141181>, interval: 1000, limit: 5000, mode: :global}
[error] GenServer {Oban.Registry, {Oban, Oban.Stager}} terminating
** (UndefinedFunctionError) function DB.PostgrexTypes.encode_params/2 is undefined (module DB.PostgrexTypes is not available)
    (transport 0.0.1) DB.PostgrexTypes.encode_params(["available", ~U[2024-10-29 07:45:43.270144Z], 5000], [Postgrex.Extensions.Raw, Postgrex.Extensions.Timestamp, Postgrex.Extensions.Int8])
    (postgrex 0.16.5) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3
    (db_connection 2.7.0) lib/db_connection.ex:1462: DBConnection.maybe_encode/4
    (db_connection 2.7.0) lib/db_connection.ex:823: DBConnection.execute/4
    (ecto_sql 3.11.3) lib/ecto/adapters/postgres/connection.ex:133: Ecto.Adapters.Postgres.Connection.execute/4
    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:996: Ecto.Adapters.SQL.execute!/5
    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
    (ecto 3.11.2) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
    (oban 2.18.0) lib/oban/engines/basic.ex:142: Oban.Engines.Basic.stage_jobs/3
    (oban 2.18.0) lib/oban/engine.ex:244: anonymous fn/4 in Oban.Engine.stage_jobs/3
    (oban 2.18.0) lib/oban/engine.ex:339: anonymous fn/3 in Oban.Engine.with_span/4
    (telemetry 1.2.1) /Users/thbar/git/transport/transport-site/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (oban 2.18.0) lib/oban/stager.ex:71: anonymous fn/1 in Oban.Stager.stage_and_notify/2
    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:1358: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.7.0) lib/db_connection.ex:1756: DBConnection.run_transaction/4
    (oban 2.18.0) lib/oban/stager.ex:70: Oban.Stager.stage_and_notify/2
    (oban 2.18.0) lib/oban/stager.ex:57: anonymous fn/2 in Oban.Stager.handle_info/2
    (telemetry 1.2.1) /Users/thbar/git/transport/transport-site/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (oban 2.18.0) lib/oban/stager.ex:56: Oban.Stager.handle_info/2
    (stdlib 4.3.1.3) gen_server.erl:1123: :gen_server.try_dispatch/4
Last message: :stage
State: %Oban.Stager{conf: %Oban.Config{dispatch_cooldown: 5, engine: Oban.Engines.Basic, get_dynamic_repo: nil, insert_trigger: false, log: false, name: Oban, node: "DESKTOP-H18V67H", notifier: {Oban.Notifiers.Postgres, []}, peer: {Oban.Peers.Postgres, []}, plugins: [{Oban.Plugins.Cron, [crontab: []]}, {Oban.Plugins.Lifeline, [rescue_after: 3600000]}, {Oban.Plugins.Pruner, [max_age: 86400]}], prefix: "public", queues: [default: [limit: 2], enroute_conversions: [limit: 10], heavy: [limit: 1], on_demand_validation: [limit: 1], resource_validation: [limit: 1], workflow: [limit: 2]], repo: DB.Repo, shutdown_grace_period: 15000, stage_interval: 1000, testing: :disabled}, timer: #Reference<0.2890691434.1772879877.130976>, interval: 1000, limit: 5000, mode: :global}
[error] GenServer {Oban.Registry, {Oban, Oban.Stager}} terminating
** (UndefinedFunctionError) function DB.PostgrexTypes.encode_params/2 is undefined (module DB.PostgrexTypes is not available)
    (transport 0.0.1) DB.PostgrexTypes.encode_params(["available", ~U[2024-10-29 07:45:44.363283Z], 5000], [Postgrex.Extensions.Raw, Postgrex.Extensions.Timestamp, Postgrex.Extensions.Int8])
    (postgrex 0.16.5) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3
    (db_connection 2.7.0) lib/db_connection.ex:1462: DBConnection.maybe_encode/4
    (db_connection 2.7.0) lib/db_connection.ex:823: DBConnection.execute/4
    (ecto_sql 3.11.3) lib/ecto/adapters/postgres/connection.ex:133: Ecto.Adapters.Postgres.Connection.execute/4
    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:996: Ecto.Adapters.SQL.execute!/5
    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
    (ecto 3.11.2) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
    (oban 2.18.0) lib/oban/engines/basic.ex:142: Oban.Engines.Basic.stage_jobs/3
    (oban 2.18.0) lib/oban/engine.ex:244: anonymous fn/4 in Oban.Engine.stage_jobs/3
    (oban 2.18.0) lib/oban/engine.ex:339: anonymous fn/3 in Oban.Engine.with_span/4
    (telemetry 1.2.1) /Users/thbar/git/transport/transport-site/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (oban 2.18.0) lib/oban/stager.ex:71: anonymous fn/1 in Oban.Stager.stage_and_notify/2
    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:1358: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.7.0) lib/db_connection.ex:1756: DBConnection.run_transaction/4
    (oban 2.18.0) lib/oban/stager.ex:70: Oban.Stager.stage_and_notify/2
    (oban 2.18.0) lib/oban/stager.ex:57: anonymous fn/2 in Oban.Stager.handle_info/2
    (telemetry 1.2.1) /Users/thbar/git/transport/transport-site/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (oban 2.18.0) lib/oban/stager.ex:56: Oban.Stager.handle_info/2
    (stdlib 4.3.1.3) gen_server.erl:1123: :gen_server.try_dispatch/4
Last message: :stage
State: %Oban.Stager{conf: %Oban.Config{dispatch_cooldown: 5, engine: Oban.Engines.Basic, get_dynamic_repo: nil, insert_trigger: false, log: false, name: Oban, node: "DESKTOP-H18V67H", notifier: {Oban.Notifiers.Postgres, []}, peer: {Oban.Peers.Postgres, []}, plugins: [{Oban.Plugins.Cron, [crontab: []]}, {Oban.Plugins.Lifeline, [rescue_after: 3600000]}, {Oban.Plugins.Pruner, [max_age: 86400]}], prefix: "public", queues: [default: [limit: 2], enroute_conversions: [limit: 10], heavy: [limit: 1], on_demand_validation: [limit: 1], resource_validation: [limit: 1], workflow: [limit: 2]], repo: DB.Repo, shutdown_grace_period: 15000, stage_interval: 1000, testing: :disabled}, timer: #Reference<0.2890691434.1772879878.130276>, interval: 1000, limit: 5000, mode: :global}
[error] GenServer #PID<0.923.0> terminating
** (UndefinedFunctionError) function TransportWeb.Presence.fetch/2 is undefined (module TransportWeb.Presence is not available)
    (transport 0.0.1) TransportWeb.Presence.fetch("explore", %{})
    (transport 0.0.1) lib/transport/realtime_poller.ex:59: Transport.RealtimePoller.viewers/0
    (transport 0.0.1) lib/transport/realtime_poller.ex:64: Transport.RealtimePoller.viewers_count/0
    (transport 0.0.1) lib/transport/realtime_poller.ex:47: Transport.RealtimePoller.handle_info/2
    (stdlib 4.3.1.3) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3.1.3) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3.1.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: :tick
State: %{}
[error] GenServer #PID<0.2035.0> terminating
** (UndefinedFunctionError) function TransportWeb.Presence.fetch/2 is undefined (module TransportWeb.Presence is not available)
    (transport 0.0.1) TransportWeb.Presence.fetch("explore", %{})
    (transport 0.0.1) lib/transport/realtime_poller.ex:59: Transport.RealtimePoller.viewers/0
    (transport 0.0.1) lib/transport/realtime_poller.ex:64: Transport.RealtimePoller.viewers_count/0
    (transport 0.0.1) lib/transport/realtime_poller.ex:47: Transport.RealtimePoller.handle_info/2
    (stdlib 4.3.1.3) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3.1.3) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3.1.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: :tick
State: %{}
[error] GenServer #PID<0.2042.0> terminating
** (UndefinedFunctionError) function TransportWeb.Presence.fetch/2 is undefined (module TransportWeb.Presence is not available)
    (transport 0.0.1) TransportWeb.Presence.fetch("explore", %{})
    (transport 0.0.1) lib/transport/realtime_poller.ex:59: Transport.RealtimePoller.viewers/0
    (transport 0.0.1) lib/transport/realtime_poller.ex:64: Transport.RealtimePoller.viewers_count/0
    (transport 0.0.1) lib/transport/realtime_poller.ex:47: Transport.RealtimePoller.handle_info/2
    (stdlib 4.3.1.3) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3.1.3) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3.1.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: :tick
State: %{}
[error] GenServer #PID<0.2055.0> terminating
** (UndefinedFunctionError) function TransportWeb.Presence.fetch/2 is undefined (module TransportWeb.Presence is not available)
    (transport 0.0.1) TransportWeb.Presence.fetch("explore", %{})
    (transport 0.0.1) lib/transport/realtime_poller.ex:59: Transport.RealtimePoller.viewers/0
    (transport 0.0.1) lib/transport/realtime_poller.ex:64: Transport.RealtimePoller.viewers_count/0
    (transport 0.0.1) lib/transport/realtime_poller.ex:47: Transport.RealtimePoller.handle_info/2
    (stdlib 4.3.1.3) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3.1.3) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3.1.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: :tick
State: %{}
[error] GenServer {Oban.Registry, {Oban, Oban.Sonar}} terminating
** (UndefinedFunctionError) function DB.PostgrexTypes.encode_params/2 is undefined (module DB.PostgrexTypes is not available)
    (transport 0.0.1) DB.PostgrexTypes.encode_params(["public.oban_sonar", ["H4sIAAAAAAAAE6tWystPSVWyUnJxDfYO8Q/Q9TC0CDMz91DSUSrIzEtXsiopKk2tBQAhUSNjJgAAAA=="]], [Postgrex.Extensions.Raw, Postgrex.Extensions.JSON])
    (postgrex 0.16.5) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3
    (db_connection 2.7.0) lib/db_connection.ex:1449: DBConnection.encode/5
    (db_connection 2.7.0) lib/db_connection.ex:1549: DBConnection.run_prepare_execute/5
    (db_connection 2.7.0) lib/db_connection.ex:1653: DBConnection.run/6
    (db_connection 2.7.0) lib/db_connection.ex:772: DBConnection.parsed_prepare_execute/5
    (db_connection 2.7.0) lib/db_connection.ex:764: DBConnection.prepare_execute/4
    (postgrex 0.16.5) lib/postgrex.ex:361: Postgrex.query_prepare_execute/4
    (oban 2.18.0) lib/oban/notifiers/postgres.ex:96: Oban.Notifiers.Postgres.notify/3
    (oban 2.18.0) lib/oban/notifier.ex:202: anonymous fn/4 in Oban.Notifier.notify/3
    (telemetry 1.2.1) /Users/thbar/git/transport/transport-site/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (oban 2.18.0) lib/oban/sonar.ex:70: Oban.Sonar.handle_info/2
    (stdlib 4.3.1.3) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3.1.3) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3.1.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: :ping
State: %Oban.Sonar{conf: %Oban.Config{dispatch_cooldown: 5, engine: Oban.Engines.Basic, get_dynamic_repo: nil, insert_trigger: false, log: false, name: Oban, node: "DESKTOP-H18V67H", notifier: {Oban.Notifiers.Postgres, []}, peer: {Oban.Peers.Postgres, []}, plugins: [{Oban.Plugins.Cron, [crontab: []]}, {Oban.Plugins.Lifeline, [rescue_after: 3600000]}, {Oban.Plugins.Pruner, [max_age: 86400]}], prefix: "public", queues: [default: [limit: 2], enroute_conversions: [limit: 10], heavy: [limit: 1], on_demand_validation: [limit: 1], resource_validation: [limit: 1], workflow: [limit: 2]], repo: DB.Repo, shutdown_grace_period: 15000, stage_interval: 1000, testing: :disabled}, timer: #Reference<0.2890691434.1772879874.129127>, interval: 5000, nodes: %{"DESKTOP-H18V67H" => -576460698933}, stale_mult: 6, status: :solitary}
[error] GenServer {Oban.Registry, {Oban, Oban.Peer}} terminating
** (UndefinedFunctionError) function DB.PostgrexTypes.encode_params/2 is undefined (module DB.PostgrexTypes is not available)
    (transport 0.0.1) DB.PostgrexTypes.encode_params(["Oban", "DESKTOP-H18V67H"], [Postgrex.Extensions.Raw, Postgrex.Extensions.Raw])
    (postgrex 0.16.5) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3
    (db_connection 2.7.0) lib/db_connection.ex:1449: DBConnection.encode/5
    (db_connection 2.7.0) lib/db_connection.ex:1549: DBConnection.run_prepare_execute/5
    (db_connection 2.7.0) lib/db_connection.ex:772: DBConnection.parsed_prepare_execute/5
    (db_connection 2.7.0) lib/db_connection.ex:764: DBConnection.prepare_execute/4
    (ecto_sql 3.11.3) lib/ecto/adapters/postgres/connection.ex:101: Ecto.Adapters.Postgres.Connection.prepare_execute/5
    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:960: Ecto.Adapters.SQL.execute!/5
    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
    (oban 2.18.0) lib/oban/peers/postgres.ex:75: anonymous fn/1 in Oban.Peers.Postgres.terminate/2
    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:1358: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.7.0) lib/db_connection.ex:1756: DBConnection.run_transaction/4
    (oban 2.18.0) lib/oban/peers/postgres.ex:74: Oban.Peers.Postgres.terminate/2
    (stdlib 4.3.1.3) gen_server.erl:1161: :gen_server.try_terminate/3
    (stdlib 4.3.1.3) gen_server.erl:1351: :gen_server.terminate/10
    (stdlib 4.3.1.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.885.0>, :shutdown}
State: %Oban.Peers.Postgres{conf: %Oban.Config{dispatch_cooldown: 5, engine: Oban.Engines.Basic, get_dynamic_repo: nil, insert_trigger: false, log: false, name: Oban, node: "DESKTOP-H18V67H", notifier: {Oban.Notifiers.Postgres, []}, peer: {Oban.Peers.Postgres, []}, plugins: [{Oban.Plugins.Cron, [crontab: []]}, {Oban.Plugins.Lifeline, [rescue_after: 3600000]}, {Oban.Plugins.Pruner, [max_age: 86400]}], prefix: "public", queues: [default: [limit: 2], enroute_conversions: [limit: 10], heavy: [limit: 1], on_demand_validation: [limit: 1], resource_validation: [limit: 1], workflow: [limit: 2]], repo: DB.Repo, shutdown_grace_period: 15000, stage_interval: 1000, testing: :disabled}, timer: #Reference<0.2890691434.1772879873.140301>, interval: 30000, leader?: true, leader_boost: 2}
[error] GenServer #PID<0.867.0> terminating
** (UndefinedFunctionError) function TransportWeb.Endpoint.config/1 is undefined (module TransportWeb.Endpoint is not available)
    (transport 0.0.1) TransportWeb.Endpoint.config({:socket, TransportWeb.UserSocket})
    (phoenix 1.7.14) lib/phoenix/socket/pool_supervisor.ex:97: Phoenix.Socket.PoolDrainer.terminate/2
    (stdlib 4.3.1.3) gen_server.erl:1161: :gen_server.try_terminate/3
    (stdlib 4.3.1.3) gen_server.erl:1351: :gen_server.terminate/10
    (stdlib 4.3.1.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.705.0>, :shutdown}
State: {TransportWeb.Endpoint, TransportWeb.UserSocket, 10000, 2000}
[error] GenServer #PID<0.866.0> terminating
** (UndefinedFunctionError) function TransportWeb.Endpoint.config/1 is undefined (module TransportWeb.Endpoint is not available)
    (transport 0.0.1) TransportWeb.Endpoint.config({:socket, Phoenix.LiveView.Socket})
    (phoenix 1.7.14) lib/phoenix/socket/pool_supervisor.ex:97: Phoenix.Socket.PoolDrainer.terminate/2
    (stdlib 4.3.1.3) gen_server.erl:1161: :gen_server.try_terminate/3
    (stdlib 4.3.1.3) gen_server.erl:1351: :gen_server.terminate/10
    (stdlib 4.3.1.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.705.0>, :shutdown}
State: {TransportWeb.Endpoint, Phoenix.LiveView.Socket, 10000, 2000}
[error] GenServer #PID<0.865.0> terminating
** (UndefinedFunctionError) function TransportWeb.Endpoint.config/1 is undefined (module TransportWeb.Endpoint is not available)
    (transport 0.0.1) TransportWeb.Endpoint.config({:socket, Phoenix.LiveReloader.Socket})
    (phoenix 1.7.14) lib/phoenix/socket/pool_supervisor.ex:97: Phoenix.Socket.PoolDrainer.terminate/2
    (stdlib 4.3.1.3) gen_server.erl:1161: :gen_server.try_terminate/3
    (stdlib 4.3.1.3) gen_server.erl:1351: :gen_server.terminate/10
    (stdlib 4.3.1.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.705.0>, :shutdown}
State: {TransportWeb.Endpoint, Phoenix.LiveReloader.Socket, 10000, 2000}
[info] GET /
[info] GET /
[debug] Processing with TransportWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Generating cached value for key home-index-stats
```

**Comment by ptitfred** [comment]
Non, pas observé en local chez moi.

**Comment by AntoineAugusti** [comment]
Jamais vu

**Comment by thbar** [comment]
Merci - bon vu que je suis le seul, je vais clôturer pour le moment, et si ça revient le ticket sera déjà là et je le ré-ouvrirai.
