### ISSUE TITLE
Creuser des erreurs 500 aléatoires

### ISSUE THREAD

**Issue by Tristramg** [etalab/transport-site#523]
C’est probablement une histoire de timeout avec data.gouv.fr. Le soucis c’est que ça affecte des pages même quand il n’y a pas besoin de taper sur data.gouv.fr. Le comportement est aléatoire et se résoud tout seul au bout de quelques minutes.

```
 2018-12-24T10:33:23+01:00 09:33:23.423 request_id=2lpjm1nujpp6jrv0uo007geh [info] Sent 500 in 5077ms
2018-12-24T10:33:23+01:00 09:33:23.426 [error] #PID<0.13331.5> running TransportWeb.Endpoint (cowboy_protocol) terminated
2018-12-24T10:33:23+01:00 Server: transport.data.gouv.fr:80 (http)
2018-12-24T10:33:23+01:00 Request: GET /datasets/versions-des-horaires-theoriques-des-lignes-du-reseau-star-au-format-gtfs/
2018-12-24T10:33:23+01:00 ** (exit) an exception was raised:
2018-12-24T10:33:23+01:00 (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
2018-12-24T10:33:23+01:00 ** (Protocol.UndefinedError) protocol String.Chars not implemented for {:error, %OAuth2.Error{reason: :timeout}}. This protocol is implemented for: Atom, BitString, Date, DateTime, Decimal, Float, Geo.GeometryCollection, Geo.LineString, Geo.MultiLineString, Geo.MultiPoint, Geo.MultiPolygon, Geo.Point, Geo.PointM, Geo.PointZ, Geo.PointZM, Geo.Polygon, Integer, List, NaiveDateTime, Postgrex.Copy, Postgrex.Query, Time, URI, Version, Version.Requirement
2018-12-24T10:33:23+01:00 (elixir) lib/string/chars.ex:22: String.Chars.to_string/1
2018-12-24T10:33:23+01:00 (transport) lib/datagouvfr/client.ex:76: Datagouvfr.Client.get_discussions/2
2018-12-24T10:33:23+01:00 (transport) lib/transport_web/controllers/dataset_controller.ex:39: TransportWeb.DatasetController.details/2
2018-12-24T10:33:23+01:00 (transport) lib/transport_web/controllers/dataset_controller.ex:1: TransportWeb.DatasetController.action/2
2018-12-24T10:33:23+01:00 (transport) lib/transport_web/controllers/dataset_controller.ex:1: TransportWeb.DatasetController.phoenix_controller_pipeline/2
2018-12-24T10:33:23+01:00 (transport) lib/transport_web/endpoint.ex:1: TransportWeb.Endpoint.instrument/4
2018-12-24T10:33:23+01:00 (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1 
```

**Comment by l-vincent-l** [comment]
Sur cette page en particulier on a besoin de datagouv pour les commentaires, est-ce que l'on veut proposer une version dégradée sans les commentaires ?

**Comment by Tristramg** [comment]
L’issue c’était de creuser les erreurs. On sait que c’est lié à des timeouts pour récupérer les commentaires. On verra plus tard si ça devient handicapant
